pnp/PnP-PowerShell

Commands/Enums/SearchConfigurationScope.cs, Commands/Search/GetSearchConfiguration.cs, Commands/Search/SetSearchConfiguration.cs
Added support for importing and exporting search settings configuration at the tenant level.
I could not use GetSearchConfiguration() from PnP.Core or the Export extension as they are hooked to Web/Site or export to file, so I added explicit code to export the settings on the tenant. Can be re-factored if Core is updated with supporting methods.
=> Added support for importing and exporting search settings configuration at the tenant level

Commands/Web/AddFile.cs
Fix for #123: Add-SPOFile -Checkout  does not update existing files when the library has the RequireCheckout -option set
=> Fix for #123: Add-SPOFile -Checkout  does not update existing files 

Commands/Admin/GetTenantSite.cs
"By default, not all returned attributes are populated. This switch populates all attributes. It can take several seconds to run. Without this, some attributes will show default values that may not be correct."
Explain what the -Detailed switch actually does.
=> Explain -Detailed switch in CetTenantSite.cs

Commands/Base/ConnectSPOnline.cs, Commands/ModuleFiles/SharePointPnP.PowerShell.2013.Commands.Format.ps1xml, Commands/ModuleFiles/SharePointPnP.PowerShell.2016.Commands.Format.ps1xml, Commands/ModuleFiles/SharePointPnP.PowerShell.Online.Commands.Format.ps1xml, Commands/Provider/SPOContentParameters.cs, Commands/Provider/SPOContentReaderWriter.cs, Commands/Provider/SPODriveCacheItem.cs, Commands/Provider/SPODriveInfo.cs, Commands/Provider/SPODriveParameters.cs, Commands/Provider/SPOProvider.cs, Commands/SharePointPnP.PowerShell.Commands.csproj, Commands/Web/GetFolderItem.cs, Documentation/GetSPOFolderItem.md
I often find that I need to know what files and folders I have in my site and a PowerShell cmdlet would come in handy. So wrote the Get-SPOFolderItem command that lists folder and file at a given path.
However even better would be navigate the site as a regular file store and be able to use commands like Get-Item, Get-ChildItem, Set-Location, Set-Content and so on. So I wrote a custom PowerShell (Drive) Provider that allow just that. 
A drive can be created with the -CreateDrive switch at Connect-SPOnline, which default creates a drive named spo:, or via the regular New-PSDrive command.
Most regular provider commands are supported, thou right now copy/move actions between sites is not supported, but piping Get-Content and Set-Content can accomplish the same thing.
To be able to show File …
=> Get-SPOFolderItem and an SPO PSProvider

Commands/ModuleFiles/SharePointPnP.PowerShell.2013.Commands.Format.ps1xml, Commands/ModuleFiles/SharePointPnP.PowerShell.2016.Commands.Format.ps1xml, Commands/ModuleFiles/SharePointPnP.PowerShell.Online.Commands.Format.ps1xml, Commands/Provider/SPODriveCacheWeb.cs, Commands/Provider/SPODriveInfo.cs, Commands/Provider/SPODriveParameters.cs, Commands/Provider/SPOProvider.cs, Commands/SharePointPnP.PowerShell.Commands.csproj
Added the ability to perform actions cross site (collections).
- The provider changes context when needed.
- Set-Location takes any valid server relative url (under the same host).
- Copy-Item and Move-Item supports copying/moving files or folders to subsites and other site collections.
- Get-ChildItem shows subsites.
=> Updated SPO PSProvider with cross site support

Commands/Utilities/SendMail.cs
Support to send e-mail using the current client context instead of from address and password. Useful when using app context, or any other context in a script where you don't want to enter the password.
=> Send email using SharePoint SendMail and using the current client context

Commands/Base/SPOWebCmdlet.cs, Commands/Base/SPOnlineConnection.cs
Updated accessibility levels for some internal methods to expose core functionality for custom powershell commandlets that are not a part of PnP. For example if someone want to create custom commandlets for a specific customer.
=> Updated accessibility levels

Commands/ModuleFiles/SharePointPnP.PowerShell.2013.Commands.Format.ps1xml, Commands/ModuleFiles/SharePointPnP.PowerShell.2016.Commands.Format.ps1xml, Commands/ModuleFiles/SharePointPnP.PowerShell.Online.Commands.Format.ps1xml, Commands/Provider/SPOProvider.cs
- Fix so the PSObject has the correct PSPath and PSParentPath when using Get-ChildItem in the SPO Provider. 
- Changed the formatting to use the PSParentPath for grouping.
- Fix bug in Set-Content to pick up newly created file
=> SPO Provider Fixes

Commands/Branding/AddNavigationNode.cs
Adds support for the `isExternal` and `asLastNode` parameters of `NavigationExtensions.AddNavigationNode` by adding `-First` and `-External` switch parameters. Excluding the switches preserves current behavior (new items are added to the end of the collection and not marked external).
=> Add support for ordering menu items and specifying external links

Commands/Branding/ConvertFolderToProvisioningTemplate.cs
The command currently doesn't appear within the right category in the PowerShell documentation.
=> Updated category for SPOFolderToProvisioningTemplate documentation

Commands/Taxonomy/ImportTaxonomy.cs
Filters any empty terms provided prior to import. Resolves #477
=> Import-SPOTaxonomy fixes

Commands/Web/SetWeb.cs
Replaced the ``String.IsNullOrEmpty`` checks with a loop over the bound parameters to allow explicit clearing of property values if desired. Resolves #455
=> Remove null and empty string checks from Set-SPOWeb to allow clearing properties

Commands/Web/GetFile.cs
Added new parameters ``AsFile`` and ``AsListItem`` and associated parameter sets to the ``Get-SPOFile`` cmdlet to allow returning the file to the pipeline as a ``File`` or ``ListItem`` object.
=> Add ability to retrieve file as File or ListItem object

Commands/Apps/UninstallAppInstance.cs
Missing `n` in command name `Uinstall-SPOAppInstance`.
This leads to this error while importing the module:
> WARNING: Some imported command names from module "SharePointPnPPowerShell2013" include unapproved verbs which might make them less discoverable.  Use the Verbose parameter for more detail or type
Get-Verb to see the list of approved verbs.
=> Typo in alias

Commands/Base/PipeBinds/RecycleBinItemPipeBind.cs, Commands/Properties/Resources.Designer.cs, Commands/Properties/Resources.resx, Commands/RecycleBin/ClearRecycleBinItem.cs, Commands/RecycleBin/ClearRecycleBinItems.cs, Commands/RecycleBin/ClearTenantRecycleBinItem.cs, Commands/RecycleBin/GetRecycleBinItems.cs, Commands/RecycleBin/MoveRecycleBinItems.cs, Commands/RecycleBin/ResetRecycleBinItem.cs, Commands/RecycleBin/ResetRecycleBinItems.cs, Commands/RecycleBin/ResetTenantRecycleBinItem.cs, Commands/SharePointPnP.PowerShell.Commands.csproj, Documentation/ClearPnPTenantRecycleBinItem.md, Documentation/ClearPnpRecycleBinItem.md, Documentation/ClearPnpRecycleBinItems.md, Documentation/GetPnPRecycleBinItems.md, Documentation/MovePnpRecycleBinItems.md, Documentation/ResetPnPTenantRecycleBinItem.md, Documentation/ResetPnpRecycleBinItem.md, Documentation/ResetPnpRecycleBinItems.md, Documentation/readme.md, HelpAttributes/CmdletHelpCategory.cs
N/A
The following new commands have been added to work with the SharePoint recycle bin:
- Clear-PnPRecycleBinItem
- Clear-PnPRecycleBinItems
- Clear-PnPTenantRecycleBinItem
- Get-PnPRecycleBinItems
- Move-PnPRecyclyBinItems
- Reset-PnPRecycleBinItem
- Reset-PnPRecycleBinItems
- Reset-PnPTenantRecycleBinItem
- Clear-PnPRecycleBinItem: Allows permanent deletion of specific item(s) from the site collection recycle bin
- Clear-PnPRecycleBinItems: Allows permanent deletion of all items from the site collection recycle bin
- Clear-PnPTenantRecycleBinItem: Allows permanent deletion of a site collection from the tenant recycle bin
- Get-PnPRecycleBinItems: Allows retrieving of all items currently in the first- and second stage site collection recycle bin
- Move-PnPRecyclyBinItems: Allows moving …
=> Added commands for all possible recycle bin operations

Commands/Lists/SetDefaultColumnValues.cs
- [ x] Bug Fix
Fixes #616 
As described in #616, the list parameter should always be provided. The cmdlet only makes sense with a given list, thus the parameter has been made mandatory
=> The List parameter should be mandatory, as mentioned in #616

Commands/Publishing/AddPublishingPage.cs
This pull request will add a -Folder parameter to the Add-PnPPublishingPage Cmdlet so that publishing pages can be created inside of folders from powershell. This functionality already exists in the OfficeDevPnP.Core project, but is not surfaced by this Cmdlet.
=> Adding Folder option to Add-PnpPublishingPage Cmdlet

Commands/Lists/AddListItem.cs
- [x ] Bug Fix
Fixes #593 
Added a item.Update() call after a User field is added. Without this, it is not possible to populate multiple User fields.
For example, before the fix, the following call would only add Person2, but not Person1 and Person3:
Add-PnPListItem -List "Sales Pipeline" -Values @{"Person1" = "user1@contoso.com"; "Person2"="user2@contoso.com"; "Person3"="user3@contoso.com"; "Title" = "Test"}
=> Fix for #593

Commands/Files/GetFile.cs, Documentation/GetPnPFile.md, Documentation/GetPnPPublishingImageRendition.md, Documentation/RemovePnPPublishingImageRendition.md, changelog.md
the ServerRelativeUrl and SiteRelativeUrl parameters are now obsolete (but will still work) and one should now use -Url. The Url parameter accepts both server and site relative urls.
=> Refactored Get-PnPFile

Commands/Lists/GetList.cs
- [ x] Bug Fix
Check if string is not null before loading properties to avoid getting ObjectReference error in the console. If list does not exist, return null.
=> Check if lists exist before loading properties

Commands/Files/CopyFile.cs
- [ x] Bug Fix
- [ x] New Feature
The existing code uses file.CopyTo which only works within the same web, while the samples stated otherwise. I have added code which allows copying of a file or folder from the current context to any other site/site collection. If source/target is the same web, it will try to use .CopyTo first.
I also added a switch **SkipSourceFolderName** to be used for folder copy if you only want the contents of the folder, and not the folder itself in the target destination.
Examples have been corrected and added more for folder copying.
=> Re-worked PnP-Copy file to work for cross site/site collection

Commands/UserProfiles/GetUserProfileProperty.cs, Commands/UserProfiles/SetUserProfileProperty.cs
- [ x] Bug Fix
On-premises CSOM support getting properties using *PeopleManager*. I moved the #if !ONPREMISES statement around the parts that relate to O365 on tenant management and encoding the claim.
Another solution would be to try/catch on *Tenant.EncodeClaim(Account)* or some other method to check if you are on a tenant or not.
=> Enable Get-PnPUserProfileProperty for on-premises

Commands/Provisioning/ApplyProvisioningTemplate.cs
Fixes #723 
I added the IgnoreDuplicateDataRowErrors switch to the ApplyProvisioningTemplate command, so a template with DataRows can be provisioned multiple times, without giving errors on duplicate data rows.
=> Added IgnoreDuplicateDataRowErrors

Commands/Base/DisconnectSPOnline.cs, Commands/Extensions/ClientObjectExtensions.cs, Commands/Provider/Parameters/SPODriveParameters.cs, Commands/Provider/SPOProvider.cs, Commands/Provider/SPOProxy/SPOProxyCmdletBase.cs, Commands/Provider/SPOProxy/SPOProxyCopyItem.cs, Commands/Provider/SPOProxy/SPOProxyImplementation.cs, Commands/Provider/SPOProxy/SPOProxyMoveItem.cs, Commands/SharePointPnP.PowerShell.Commands.csproj
This need PR  [PnP-Sites-Core/#1065](https://github.com/SharePoint/PnP-Sites-Core/pull/1065) to be able to save files from SharePoint to FileSystem
Proxy cmdlets to allow the usage of the standard cmdlets Copy-Item and Move-Item between the FileSystem provider and the SharePoint provider. It consist of:
- PnP-Proxy-cmdlets that's handle the actual copying/moving if FileSystem and SharePoint is involved (otherwise the request is transferred to the standard cmdlets).
- Aliases to take over the standard cmdlets names. The aliases will be inserted when a SharePoint drive is created (if not the switch -NoProxyCmdLets is used).
Also in this PR
- Corrected the behavior of Copy-Item to correlate with the FileSystem provider.
- Workaround for CSOM v15 where deleted items are returned from object …
=> Proxy cmdlets for Copy-Item and Move-Item

.gitignore, Commands/SharePointPnP.PowerShell.Commands.csproj, Commands/Web/SetWebPermission.cs, Tests/SharePointPnP.PowerShell.Tests.csproj, Tests/WebTests.cs
Fixes #716
Introduced a new cmd-let **Set-PnPWebPermission** to manage web permissions like **Set-PnPListPermission** for lists.
=> New cmd-let Set-PnPWebPermission to manage permissions of a web

Commands/Lists/SetListItemPermission.cs, Commands/Lists/SetListPermission.cs, Commands/SharePointPnP.PowerShell.Commands.csproj
Commandlet to work with permissions for a list item.
(A small bug fix on resolving users on setpermissions on a list)
Some thoughts - Set-PnPList also has functions to break inheritance, and a separate commandlet to add/remove roles. No functionality to restore inheritance. @erwinvanhunen, would it be useful to add ClearExisting/InheritPermissions switches to the Set-PnPListPermission cmdlet as well? And the Set-PnPListItem has no functionality to break inheritence.
=> Set list item permissions

Commands/Search/SetSearchConfiguration.cs
Fixes [Set-PnPSearchConfiguration is not working with Tenant Scope](https://github.com/SharePoint/PnP-PowerShell/issues/745)
Changed import to filepath instead of file content (configuration).
=> Changed import to filepath instead of file content.

Commands/Taxonomy/NewTerm.cs
None
When using `New-PnPTerm` it returns the Term Set it was created in, not the term. This update fixes that.
=> fix to return the newly created term not the termset

Commands/Files/RemoveFile.cs, Commands/Files/RemoveFolder.cs, Commands/Lists/RemoveList.cs, Commands/Lists/RemoveListItem.cs, Documentation/RemovePnPFile.md, Documentation/RemovePnPFolder.md, Documentation/RemovePnPList.md, Documentation/RemovePnPListItem.md
None
New Recycle switches on `Remove-PnPListItem`, `Remove-PnPList1`, `Remove-PnPFile` and `Remove-PnPFolder`
Should deprecate `MoveListItemToRecycleBin`?
=> added recycling options to remove commands

Commands/Provisioning/GetProvisioningTemplate.cs, Documentation/GetPnPProvisioningTemplate.md
Continuation of the PR https://github.com/SharePoint/PnP-Sites-Core/pull/1222, related to the https://github.com/SharePoint/PnP-Sites-Core/issues/1208 issue.
Content types provision fails if the same content type already exists in the target and is read only. This is the case when the CT is provisioned in the target through content type syndication.
This PR includes a new switch parameter to the Get-PnPProvisioningTemplate command, that allows excluding these CTs. 
PnP-Sites-Core components has already been updated to support this scenario.
=> Added the ExcludeContentTypesFromSyndication parameter to the Get-PnPProvisioningTemplate command

Commands/Admin/GetTenantSite.cs
Changed the cmdlet to use GetSitePropertiesFromSharePointByFilters, which allows retrieval of all site types.
Added option to filter by WebTemplate or Filter param, which supports Url wildcard at least. Could not find documentation on what other filters are possible,
=> Improve get tenant site to support all site types and use newer CSOM API

Commands/Files/GetFile.cs
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/1007
Added -ThrowExceptionIfFileNotFound flag to Get-PnPFile -AsListItem which will throw a PSArgumentException if the file provided can not be found. If the flag is not provided, it will return an empty response to allow backwards compatibility.
=> Added Get-PnPFile -AsListItem -ThrowExceptionIfFileNotFound flag

Commands/Taxonomy/GetTerm.cs, Commands/Taxonomy/NewTerm.cs, Documentation/GetPnPUnifiedGroup.md
None
Trying to add or get a term with an ampersand (&) errored. Using method NormalizeName to resolve.
Ref: https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.taxonomy.taxonomyitem.normalizename.aspx
=> fix to normalize term name

Commands/Lists/GetList.cs
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/947
Added -ThowExceptionIfListNotFound flag to indicate an exception should be thrown if a list is requested that does not exist. If not provided, the default behavior of returning an empty response is returned for backwards compatibility.
=> Get-PnPList throw exception list not found

Commands/Base/ConnectOnline.cs
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/964
Added -IgnoreSslErrors option to Connect-PnPOnline to ignore any kind of SSL related issues when connecting to a SharePoint farm using i.e. self signed certs
=> Adding -IgnoreSslErrors option to Connect-PnPOnline

Commands/Branding/AddCustomAction.cs, Documentation/AddPnPCustomAction.md
The Add-PnPCustomAction cmdlet allows to add a custom action to associate with SPFx extensions through the ClientSideComponentId.
- The ClientSideComponentProperties, however, are not required
- For the ListviewCommandSet extension, we need to set the RegistrationId and RegistrationType parameters that were not included in the ParameterSet.
This PR fixes those two "issues"
=> Fixes inconsistencies in Add-PnPCustomAction cmdlet parameters

Commands/Base/PipeBinds/ClientSidePagePipeBind.cs, Commands/ClientSidePages/AddClientSidePage.cs, Commands/ClientSidePages/AddClientSidePageSection.cs, Commands/ClientSidePages/AddClientSideText.cs, Commands/ClientSidePages/AddClientSideWebPart.cs, Commands/ClientSidePages/GetAvailableClientSideComponents.cs, Commands/ClientSidePages/GetClientSidePage.cs, Commands/ClientSidePages/RemoveClientSidePage.cs, Commands/ClientSidePages/SetClientSidePage.cs
Fixes typos and documentation mismatch in PR #1054 
- Fixes typos, docs mismatch and improve consistency across Doc examples
- Converted CommentsEnabled argument to be a switch parameter instead of a nullable boolean
- The AddPnPClientSidePage cmdlet has now the Name argument as first position (It allows to use "Add-PnPClientSidePage "mypage" )
- Ensures the ClientSidePagePipeBind has always a value for the _name field. When the piped object is a ClientSidePage object, the name of the underlying file is fetched.
=> Fixes typos in documentation + changed the CommentsEnabled argument type

Commands/RecycleBin/GetTenantRecycleBinItem.cs
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/1047 to the proper dev branch
Added description on this command to make clear that you need to connect to the -admin endpoint of SPO in order for the command to work. Otherwise you'll get a 403.
Retested this: when using a clientid/clientsecret and connecting to a normal sitecollection, it can't auto switch to the -admin context for this command and will throw:
> Get-PnPTenantRecycleBinItem : The remote server returned an error: (401) Unauthorized.
=> Add description to Get-PnPTenantRecycleBinItem to clarify -admin requirement

Commands/Lists/SetListItemPermission.cs
https://github.com/SharePoint/PnP-PowerShell/issues/1046
Examples were mentioning using Set-PnPListPermission while it should be Set-PnPListItemPermission
=> Fixed incorrect examples of Set-PnPListItemPermission

Commands/Lists/GetListItem.cs
N/A
Changed example on using -Fields argument as it isn't clear nor logical how to use the fields. The sample showed:
`Get-PnPListItem -List Tasks -Fields \"Title\",\"GUID\"`
Most logical would then be to expect to be able to pipe it to | select Title,GUID, but that doesn't work. Also another logical expectation would be to be able to assign the output to a variable and use it as a property on there, which also doesn't work.
Only way I found to be able to access the fields requested through the -Fields argument is to get them from the .FieldValues property on the result, thus this would be an example where you actually see what you retrieve:
`(Get-PnPListItem -List Tasks -Fields \"Title\",\"GUID\").FieldValues`
Therefore the sample update to show an end to end sample of how to make use of …
=> Updated example on Get-PnPListItem

Commands/Principals/GetUser.cs
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/1112
Added -WithRightsAssigned flag to Get-PnPUser to only return users that have any kind of access rights on the site as opposed to the regular Get-PnPUser which includes any user ever having had access to the site and still existing in the User Information List.
=> Added -WithRightsAssigned to Get-PnPUser

Commands/Base/ConnectOnline.cs, Commands/Base/DisconnectSPOnline.cs, Commands/Base/PnPCmdlet.cs
PnP powershell cmdlets cannot be used in multi-threaded environment (e.g. Azure Functions) because of shared static connection object.
New parameter to base pnpcmdlet to accept a connection object and use its ClientContext instead of static, if specified. Changes to Connect/Disconnect-PnPOnline to return/accept connection object. Not sure regarding Disconnect-PnPOnline though, it does not seem to do anything with connection, except setting static object reference to NULL, but does some changes to sessionstate config.
=> non-static connection support

Commands/Events/RemoveEventReceiver.cs, Commands/Properties/Resources.Designer.cs, Commands/Properties/Resources.resx
N/A
Made it possible to not specify an Identity which will then go through each event receiver and ask if it should be removed, minor code cleanup, allowed usage of -Confirm to bypass confirmation question. Left -Force in place for backwards compatibility. Made the confirmation question mention clearly which event receiver is about to be deleted. Updated samples and help text.
=> Allow remove all eventreceivers with Remove-PnPEventReceiver

Commands/Admin/GetTimeZoneId.cs, Commands/Base/PipeBinds/EventReceiverPipeBind.cs, Commands/Events/GetEventReceiver.cs, Commands/Events/RemoveEventReceiver.cs, Commands/Properties/AssemblyInfo.cs, Commands/Properties/Resources.Designer.cs, Commands/Properties/Resources.resx, Commands/SharePointPnP.PowerShell.Commands.csproj, Documentation/GetPnPEventReceiver.md, Documentation/RemovePnPEventReceiver.md
N/A
Introduced EventReceiver PipeBind. Added ability to Get and Remove EventReceivers by their name instead of only their Id. Allowed passing results from a filtered Get-PnPEventReceiver to Remove-PnPEventReceiver to remove them. Had to remove the List\Web specification in the remove confirmation question as when passing a EventReceiver instance we don't know to which scope it belongs. Updated samples.
This PR complements PR https://github.com/SharePoint/PnP-PowerShell/pull/1088.
I couldn't get the .md file excluded. I didn't make any manual changes to it. Just ignore it.
=> Introduced EventReceiverPipeBind

Commands/Lists/SetList.cs
Fixes #1343 
Fixes issue in Set-PnPList: EnsureProperties remote call resets previously updated Title/Hidden, so should be executed before updating any property in List object
=> fix for issue 1343

Commands/Web/GetSubwebs.cs, Documentation/GetPnPSubWebs.md
N/A
Changed inheritance to PnPWebRetrievalsCmdlet so it also supports the -Include argument. Discussed in https://github.com/SharePoint/PnP-PowerShell/pull/973.
=> Added support for -Include in Get-PnPSubWebs

Commands/UserProfiles/GetUPABulkImportStatus.cs, Commands/UserProfiles/NewUPABulkImportJob.cs
This PR contains a small fix that excludes O365 only commands to be compiled when configuration is 15 or 16.
=> Exclude O365 only commands from on premises compilation

Commands/Base/ConnectOnline.cs, Commands/Base/SPOnlineConnectionHelper.cs
None
SharePoint on-premise supports multiple identity providers. The page /_trust/default.aspx evaluates a request parameter named "trust" to identify the TrustedLoginProvider by name (Microsoft.SharePoint.IdentityModel.Pages.TrustedProviderSignInPage, member: LoginProvider)
This PR adds a new parameter named "LoginProviderName" to the Connect-SPOnline command and passes it as querystring while determining the wsfed parameters while creating a Adfs based client-context.
If the parameter is ommited, the old behaviour applies.
=> Added optional parameter LoginProviderName

CHANGELOG.md, Commands/Search/GetSearchCrawlLog.cs, Commands/SharePointPnP.PowerShell.Commands.csproj
Commandlet to access crawl log entries in SharePoint Online.
=> Added cmdlet for fetching crawllog entries.

Commands/Admin/GrantHubSiteRights.cs
Updated help documentation with example.
Updates to help documentation for Grant-PnPHubSiteRights cmdlet
=> Update GrantHubSiteRights.cs help documentation

Commands/Files/AddFile.cs
N/A
Added the ability to optionally specify a filename to assign to a file when uploading it. Currently the filename in SharePoint needs to match the filename it has on your local machine from where you are uploading it with Add-PnPFile. I've often been in situations with customers where you want to give it a different name in SharePoint than it has on your local machine. I.e. when uploading large amounts of the same document for creating a load test set. By allowing -FileName to be used now you have a one line Add-PnPFile -Path C:\somefile.txt -FileName differentname.txt -Folder "Shared Documents" option now to achieve this in 1 step.
=> Allow -FileName with Add-PnPFile -Path

Commands/Lists/GetListItem.cs
N/A
I've marked the ListPipeBind as the default pipebind to align with Add-PnPListItem and Remove-PnPListItem where this was already the case. This would now allow a nice chaining of the following methods to retrieve list items from a list:
`
Get-PnPList -Identity "Tasks" | Get-PnPListItem
`
The same could be done already for Get-PnPList -Identity "Tasks" | Add-PnPListItem and Get-PnPList -Identity "Tasks" | Remove-PnPListItem but not for Get-PnPListItem which is weird and inconsistent.
=> Added default pipebind to Get-PnPListItem

Commands/DocumentSets/AddDocumentSet.cs
https://github.com/SharePoint/PnP-PowerShell/issues/644
As described in https://github.com/SharePoint/PnP-PowerShell/issues/644 when trying to create a new Document Set using:
Add-PnpDocumentSet -Name "Test1" -List "Shared Documents" -ContentType "Documentset"
It does create a folder in the document library, but it doesn't apply the document set content type to it. This is because the content type is currently being retrieved from the web. While assigning the default  Document Set content type to a document library however, it automatically creates an inheritance of it with it's own ID. Trying to create the document set with the document set ID of the web won't work in this case as it doesn't exist on the list. The code adjustment I checked in ensures that now any of these usages of the …
=> Add get content type from list with doc set

Commands/Admin/NewSite.cs
N/A
Clarified purpose of Alias parameter in New-PnPSite as it wasn't clear to me from the current Get-Help description what it was for. Also added that it could also be that it gets created under /teams/ instead of /sites/ based on the configuration selected under Settings in SharePoint Online Admin.
=> Clarified purpose of Alias argument in New-PnPSite

Commands/Admin/NewTenantSite.cs
No related - loosely related to #1730 
Minor changes to the documentation, the referenced LocaleId on MSDN doesn't contain any references to the LocaleId as an Integer. Suggested running command to get directly from SharePoint.
=> Updated documentation to get the LocaleIds from SharePoint

Commands/Files/CopyFile.cs, Tests/FilesTest.cs, Tests/PSTestScope.cs, Tests/SharePointPnP.PowerShell.Tests.csproj, Tests/TestCommon.cs
- [x ] Bug Fix
Fixes #1051 
To help diagnose issue #1051, I have added some tests for GetFile and CopyFile. This also required adding a second ClientContext for another site collection to test copy between two different site collections - however, I think that there must be a better way to handle this.
This also includes a change to CopyFile so that it allows files to be uploaded with ampersands and other characters which are now allowed in SharePoint Online.
=> Support all characters for copy pnp file

Commands/RecycleBin/GetTenantRecycleBinItem.cs
N/A
Added -IncludeModernSites switch to Get-PnPTenantRecycleBinItem to also include modern sites in the tenant scoped recycle bin. Without it, it will only return classic sites being in the tenant scoped recycle bin
=> Get-PnPTenantRecycleBinItem to also include modern sites

Commands/Base/DisablePowerShellTelemetry.cs, Commands/Base/EnablePowerShellTelemetry.cs
N/A
When enabling or disabling  telemetry using Enable-PnPPowerShellTelemetry and Disable-PnPPowerShellTelemetry without having set up a connection first, it would throw a nullreference exception. As far as I can judge from the code, the most important thing is for it to write allow or disallow to the .pnppowershelltelemetry file in the user profile root folder, so this will work perfectly fine without an active connection as well. Changing this code helps in automatically setting up environments and installing PnP PowerShell and disabling telemetry on them before having an environment available to connect to. Also added a sample for using Force and removed unused usings.
=> Changed Enable\Disable telemetry to work without a connection

Commands/Admin/GetStorageEntity.cs, Commands/Admin/RemoveStorageEntity.cs, Commands/Admin/SetStorageEntity.cs
NA
This PR does an additional null check for the storage entities commandlets.
When you run execute them on brand new tenants which don't have tenant app catalog configured, PnP PowerShell throws `Object reference not set` error.
=> Fix: Additional null check while processing storage entities

Commands/Lists/SetListItemPermission.cs
Mentioned in #1691 
Added SystemUpdate flag support while modifying list item permissions.
Have kept the default behaviour as it is. 
When the flag is set, it wont create a new version or trigger MS flow.
=> Featue : Set-PnPListItemPermission , added SystemUpdate support while modifying permissions

Commands/Utilities/FileUtilities.cs
The name doesn't add meaning to the code so it can be inlined
=> chore: Refactor istrue result variable

Commands/Apps/AddApp.cs, Commands/Apps/GetApp.cs, Commands/Apps/InstallApp.cs, Commands/Apps/PublishApp.cs, Commands/Apps/RemoveApp.cs, Commands/Apps/UnpublishApp.cs, Commands/Apps/UpdateApp.cs, Commands/Base/PipeBinds/AppMetadataPipeBind.cs
requires https://github.com/SharePoint/PnP-Sites-Core/pull/2074, partially implements #1812
This pull request enables the SPFx app specific Cmdlets for SharePoint 2019. The groundwork was done in PR https://github.com/SharePoint/PnP-Sites-Core/pull/2074 and that PR has to be merged, before this PR can be processed.
=> Added support for SPFx app deployment for SP 2019 on premises

Commands/Base/SPOnlineConnection.cs
N/A
Fixing GetAzureADCredentialsContext not available in on premises thus the code not compiling in SharePoint 2019 mode
=> Fixing GetAzureADCredentialsContext not available on prem issue

Commands/Graph/RemoveUnifiedGroup.cs
N/A
Added ValueFromPipeline to allow for passing in filtered unified groups, fixed documentation errors as it is not possible to pass in multiple groups without doing a pipe unlike the help text suggested, added sample of using a pipe with the new ValueFromPipeLine to delete all public Office 365 Groups, removed unused usings to tidy up the code
=> Added ValueFromPipeline to Remove-PnPUnifiedGroup

Commands/Graph/NewUnifiedGroup.cs, Commands/Graph/SetUnifiedGroup.cs
NA
Added support to optionally create MS Teams team while provisioning O365 group as well as while modifying the group's properties.
Also, added named parameters in the methods for better readability, clarity and to reduce ambiguity as I was initially a bit confused while testing this out. Please remove it if not needed :)
=> Feature : Added support for Creating MS Teams while provisioning/modifying groups

Commands/Admin/AddOffice365GroupToSite.cs
Depends on PR https://github.com/SharePoint/PnP-Sites-Core/pull/2114 
This PR adds the ability to specify HubSiteId property as well as additional owners when groupify-ing the site collection. 
It depends on the above mentioned PR in the PnP Sites core repository to be merged before this PR is merged in the PnP PowerShell repository
=> Feature : Added support for HubSiteId and Owners while groupifying site

Commands/Base/ConnectOnline.cs, Commands/Base/SPOnlineConnectionHelper.cs
None
https://github.com/SharePoint/PnP-Sites-Core/pull/2050
This pull request contains an enhancement with which the authentication to a SharePoint server using an ADFS instance is possible by using kerberos authentication. Currently authenticating via ADFS is only possible with login/password and using a X.509 certificate. For a justification refer to [PR #2050 in PnP-Sites-Core](https://github.com/SharePoint/PnP-Sites-Core/pull/2050).
**Sample**
```Powershell
$ Connect-PnpOnline -Url https://sharepoint.onpremisses.local -Kerberos -UseAdfs
```
Secondly the method `GetAdfsConfigurationFromTargetUri` from …
=> Connect-PnpOnline: Kerberos authentication using ADFS

Commands/Branding/AddCustomAction.cs
Fixes #2019 
Fixed the issue of adding User custom action for SP 2019 with ClientSideComponentId.
While we changed the compiler directives for ClientSideComponentId and ClientSideComponentProperties, looks like we missed it in the command execution.
=> Fix: Support for ClientSideComponentId while adding custom action in SP 2019

Commands/Branding/AddCustomAction.cs
N/A
Additional changes to allow for SPFx Application Extensions which are deployed tenant wide to be enabled on individual sites through adding a CustomAction using PnP PowerShell on SharePoint 2019.
Test this by creating a new Application Extension and running:
Add-PnPCustomAction -Name "Test" -Title "Test" -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentId <guid from manifest json>
It should now show the dialog on every modern page of the site where you connected to.
=> Allow for SPFx Application Extension deployment through CustomAction on SP2019

Commands/Base/SPOnlineConnection.cs
N/A
When connecting to the non admin part of SharePoint Online, i.e. https://koenzomers.sharepoint.com using -WebLogin to deal with two factor authentication, then running Get-PnPWebTemplates, it would throw a fuzzy NullReference exception. This is because it tries to clone the context to the koenzomers-admin.sharepoint.com URL as it concerns an admin cmdlet. This fails because it used the WebLogin. It then tries to create a new security context using the CurrentConnection.PSCredential, but that is NULL with a WebLogin thus a NullReference exception gets thrown. This fix at least ensures a 401 unauthorized gets thrown instead of a NullReference exception. Still not ideal, but not sure under what circumstances I could avoid the rethrow of the exception so the clear "You are not in admin …
=> Avoiding nullreference exception with Get-PnPWebTemplates

Commands/Provisioning/Site/ApplyProvisioningTemplate.cs
N/A
Added TemplateId parameter to allow for specifying which ProvisioningTemplate in an XML file to apply. Use it like: 
`Apply-PnPProvisioningTemplate -Path .\template.xml -TemplateId "TemplateOne"`
With the template.xml file being something like:
> <?xml version="1.0" encoding="utf-8" ?>
> <pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema">
>   <pnp:Templates ID="templates">
>     <pnp:ProvisioningTemplate ID="TemplateOne" DisplayName="One" Version="1.0">
>      
>     </pnp:ProvisioningTemplate>
> 
>     <pnp:ProvisioningTemplate ID="TemplateTwo" DisplayName="Two" Version="1.0">
>   
>     </pnp:ProvisioningTemplate>
> 
>   </pnp:Templates>
> </pnp:Provisioning>
Before, without being able to provide a TemplateId, it would always take the last …
=> Allow specifying a Template Id with Apply-PnPProvisioningTemplate

Commands/Base/SPOnlineConnectionHelper.cs
This issue has been discovered while using PR #2068 in our Azure DevOps scripts for an on premises environment.
If a script is started with CurrentCredentials, the Credentials object of the context is empty. This causes an issue with REST based calls that construct their own `HttpClient `, as the `UseDefaultCredentials` flag on each instance of the `HttpClient` has to be set. As an alternative, the Credentials object can be set on the context to the `CredentialCache.DefaultNetworkCredentials` which is the same as using the `UseDefaultCredentials` flag.
=> Use DefaultNetworkCredentials if the current credentials should be used

Samples/SharePoint.ConnectUsingAppPermissions/ReadMe.md
- [X ] Bug Fix
Two typos: "registraion" -> "registration", "SahrePoint" -> "SharePoint"
The last line of the "New-PnPAzureCertificate" block was just ".\pnp.pfx #Install certificate". Not sure what was the intended way of installing the certificate but I added a call to Install-PfxCertificate.
=> Fixed two typos; added missing line to install pfx

Commands/Lists/AddListItem.cs, Commands/Lists/SetListItem.cs
N/A
Extended the AddListItem and SetListItem commands to add a parameter to set the Retention Label if it exists on the site.  If the label doesn't exist on the site, the command completes and issues a warning rather than throwing an exception.  For SharePoint Online only.
=> Feature: Add (retention) Label parameter to Add/Set-PnPListItem

Commands/Base/DisconnectSPOnline.cs, Commands/Base/PipeBinds/UserPipeBind.cs, Commands/Base/SPOnlineConnection.cs
None
This PR fixes issues reported by static analysis, in particular:
- Disconnect-PnPOnline throwing a NullReferenceException when not connected yet
- UserPipeBind throwing a NullReferenceException when the User Id (number) is specified
- Typo in SPOnlineConnection constructor ignoring ConnectionMethod parameter
Overall I would say the code quality of this project is high as almost no real issue were found (after filtering out the false positives)
=> Fix issues reported by static analysis - Bugs

Commands/Admin/NewSite.cs
Fixes #2262 
This PR adds the owner parameter for communication sites which is necessary while creating sites in app-only context.
=> Added Owner parameter for communication sites

Commands/WebParts/AddClientSideWebPart.cs
N\A
As SharePoint Server 2019 supports modern pages, it contains the same basic APIs as SharePoint Online, so this PR enables the Add-PnPClientSideWebPart cmdlet for use on SharePoint Server 2019
=> Feature: Enables Add-PnPClientSideWebPart for SP2019

Commands/ClientSidePages/GetAvailableClientSideComponents.cs, Commands/ContentTypes/AddContentTypeToList.cs, Commands/ContentTypes/GetContentType.cs, Commands/Diagnostic/MeasurePnPList.cs, Commands/DocumentSets/AddDocumentSet.cs, Commands/Events/RemoveEventReceiver.cs, Commands/Fields/AddField.cs, Commands/InformationManagement/GetListInformationRightsManagement.cs, Commands/InformationManagement/SetListInformationRightsManagement.cs, Commands/Lists/GetListItem.cs, Commands/Lists/MoveListItemToRecycleBin.cs, Commands/Lists/RemoveListItem.cs, Commands/RecordsManagement/ClearListItemAsRecord.cs, Commands/RecordsManagement/SetListItemAsRecord.cs, Commands/RecordsManagement/TestListItemIsRecord.cs, Commands/Workflows/GetWorkflowSubscription.cs
None
This PR adds some null-checks for List/Page parameters to Cmdlets to show a clear message to the user instead of a generic "Object reference not set to an instance of an object" which is often confusing (what was null ? something I passed as parameter ?)
Most of the affected cases are about ListPipeBind, with only 1 case about ClientSidePagePipeBind .
Output with this PR:
Here's a list of commands that reproduce all the affected cases handled by this PR:
```powershell
Test-PnPListItemIsRecord -List "a" -Identity 4
Clear-PnPListItemAsRecord -List "a" -Identity 4
Set-PnPListItemAsRecord -List "a" -Identity 4
Move-PnPListItemToRecycleBin -List "a" -Identity 4
Get-PnPAvailableClientSideComponents -Page "a.aspx"
Add-PnPContentTypeToList -List "a" -ContentType "Item"
Add-PnPDocumentSet …
```
=> Fix issues reported by static analysis - Better exception messages

Commands/Admin/NewSite.cs
Partially fixes #2309
In the New-PnPSite the ParameterSetName was checked against a string literal and not the refactored const field, that was renamed. Because of this the SiteDesignId was never set on the creationInformation object when supplying a SiteDesignId when calling New-PnPSite.
=> New-PnPSite doesn't apply site design when using SiteDesignID parameter

Commands/Site/SetSite.cs
No
Fixed incorrect usage of SwitchParameter for several parameters SetSite
It was only possible to set many of the switch parametes to true (present). It was not possible to set it to false.
This affected these parameters:
NoScriptSite
CommentsOnSitePagesDisabled
DisableFlows
SocialBarOnSitePagesDisabled
DisableSharingForNonOwners is also implemented in this way, but there seems to be no way to enable sharing for non owners using CSOM, so it has been left untouched.
=> Fixed incorrect usage of SwitchParameter for several parameters SetSite

Commands/Base/PnPAdminCmdlet.cs
N/A
Fixed issue when connecting to single level domain (SLD) URLs
BaseUrl in PnPAdminCmdlet would then be **http://sld.** and not **http://sld** as expected (extra dot at the end)
SLD ULRs can exist in on-prem dev environments
=> Fixed issue when connecting to single level domain URLs

Commands/Admin/NewTenantSite.cs
N/A
Made TimeZone an optional parameter for New-PnPTenantSite as OnPrem does not consider that value when creating new sites.
=> Disabled TimeZone as mandatory parameter for New-PnPTenantSite

Commands/Principals/GetUser.cs
When running Get-PnPUser against a subweb, to which not all groups were granted access, a wrong set of users was returned.
For example:
/sites/test: user1, user2, group1(user3,user4), group2(user5)
/sites/test/private: user1,group2(user5)
Previously, this returned user1, user3, user4, user5.
Now it correctly returns user1, user5
=> GetUser - Updated group logic to only add users in groups with access rights

Commands/Base/PnPGraphCmdlet.cs, Commands/Base/TokenHandling.cs
None
Fix Get-PnPAccessToken throwing NullReferenceException in these cases:
- No connection made yet, i.e. as first command in a new PowerShell session
- No PowerShell Credentials available, i.e. after calling Connect-PnPOnline -AppId <appid> -AppSecret <appsecret>
A more clear error message is returned in this case "No Azure AD connection, please connect first with Connect-PnPOnline -Graph, Connect-PnPOnline -Scopes or Connect-PnPOnline -AppId -AppSecret -AADDomain"
Before this PR:
After this PR:
=> Fix Get-PnPAccessToken throwing NullReferenceException

Commands/RecycleBin/GetRecycleBinItem.cs
Fixes #2315 
In SPO/SP2016, in certain cases when executing Get-PNPRecycleBinItem,
you could encounter ListViewThreshold errors. The RowLimit parameter
allows you to specify the amount of results you would like using a
method added in the [2016 CSOM library](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt684126(v%3Doffice.15). This parameter is hidden from
SP2013.
=> Added RowLimit param to Get-PnPRecycleBinItem

Commands/Base/PipeBinds/PagePipeBind.cs, Commands/ClientSidePages/ConvertToClientSidePage.cs
N/A
If using:
```powershell
ConvertTo-PnPClientSidePage -Identity "Alex&#39;s Blog Post" -Overwrite -TargetWebUrl "https://contoso.sharepoint.com/sites/AlexBlog" -KeepPageCreationModificationInformation -PostAsNews -SetAuthorInPageHeader -DelveKeepSubTitle -Verbose -DelveBlogPage
```
It would not match any page and throw a nullreferenceexception. Fixed the code so it shows a message that the page could not be found instead. Also fixed that if the page contains specific characters such as & like in "Alex&#39;s Blog Post #1" that it will HTML Encode the name first before feeding it it to the CAML query, otherwise it would never find and return the page.
=> Fixing issue matching Delve Blog page with ConvertTo-PnPClientSidePage

Commands/Graph/GetUnifiedGroup.cs, Commands/Graph/GetUnifiedGroupMembers.cs, Commands/Graph/GetUnifiedGroupOwners.cs, Commands/Graph/NewUnifiedGroup.cs, Commands/Graph/RemoveUnifiedGroup.cs, Commands/Graph/SetUnifiedGroup.cs
N/A
Added to the help text of each of the *-PnPUnifiedGroup* commands the permissions it needs to have in Azure Active Directory to be able to perform the operation.
=> Added permissions required for each of the *-PnPUnifiedGroup* commands

Commands/Fields/AddField.cs
Fixes #1811 , #1488
Requires https://github.com/SharePoint/PnP-Sites-Core/pull/2373
This Pull Request fix the creation of Calculated fields.
The Calculated field type requires a "\<Formula>" child node and a ResultType attribute in the CAML definition that the previous code didn't specify on the creation of the field but would try to set after. 
The Formula is mandatory on creation so the command would fail with an error message
-ResultType optional parameter is added also, defaulting to "Text".
The Pull Request contains 2 commits, with the latest version targeting the latest version of https://github.com/SharePoint/PnP-Sites-Core/pull/2373
Here's a script to reproduce the issue and to test the Pull Request
```powershell
$credentials = get-credential
$siteUrl = "<enter a SPO site …
```
=> Fix creation of Calculated fields

Commands/Branding/AddCustomAction.cs
N/A
Enabled a few parameters for Add-PnPCustomAction command in the "Client Side Component Id" parameter set that was incorrectly disabled for SP2019.
Also enabled Sequence in the same parameter set for both Online and SP2019.
=> Fix missing parameters in Add-PnPCustomAction command for SP2019

Commands/Provisioning/Site/ApplyProvisioningTemplate.cs
N/A
Resolved issue when executing Apply-PnPProvisioningTemplate -InputInstance from the root of a drive. This would throw a vague connectionString error:
With this fix it will now work:
Have taken a new empty pnp provisioning template here for the sake of demonstration of the issue. It makes no difference if an actual template is being used. If you execute it from the root using -InputInstance, it will never work.
=> Bugfix Apply-PnPProvisioningTemplate -InputInstance from root

Commands/Base/SPOnlineConnectionHelper.cs
N/A
When connecting using `Connect-PnPOnline -Graph` and canceling out of the polling for authentication results using CTRL+C, it would throw a NullReference exception. Fixed so that it doesn't throw the exception anymore but instead nicely shows that no token has been received.
=> Fixed canceling connecting using Connect-PnPOnline -Graph would throw NullRef

Commands/Base/PnPCmdlet.cs
Not sure
I've noticed a small but annoying issue with cmdlets derived from PnPCmdlet. If cmdlet returns a collection of objects and piped with Select-Object with "First" parameter, then result of Select-Object is only written to console but not to variable. For example:
"$g = Get-PnPGroup | Select -First 1", will result in outputting first group object to console, but $g variable is not set.
I've found out that Select-Object with First parameter will eventually throw PipelineStoppedException (when specified amount of objects is written to pipeline) to make piped command stop execution. I guess that this behavior is not specific to Select-Object and may be used by other cmdlets as well. But when exception is caught in PnPCmdlet, pipeline behaves weirdly after that. It does not write …
=> Do not suppress PipelineStoppedException

Commands/Apps/AddApplicationCustomizer.cs, Commands/Branding/AddCustomAction.cs
N/A
Adding HostProperties support to Add-PnPCustomAction using -ClientSideComponentProperties argument. See https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/preallocated-space-placeholders for documentation on what this can be utilized for.
Depends on https://github.com/SharePoint/PnP-Sites-Core/pull/2526 to be merged first in PnP Sites Core.
=> Adding HostProperties support to Add-PnPCustomAction

Commands/Files/AddFolder.cs
Fixes #1892
This PR pipes out the Microsoft.SharePoint.Client.Folder object created by Add-PnPFolder command, allowing usage like
```powershell
$folder = Add-PnPFolder ...
```
=> Pipe out the Folder created by Add-PnPFolder

CHANGELOG.md, Commands/SharePointPnP.PowerShell.Commands.csproj, Commands/Taxonomy/GetTerm.cs, Commands/Taxonomy/NewTerm.cs, Commands/Taxonomy/NewTermLabel.cs
=> Resubmit of PR2474

Commands/Workflows/StartWorkflowInstance.cs
Fixes #2482
Updates the examples in Start-PnPWorkflowInstance with the correct syntax.
By inspecting the way WorkflowSubscriptionPipeBind works it doesn't seem to support the Workflow name as parameter so I changed it to a generic $subscription variable.
=> Fix examples in Start-PnPWorkflowInstance

CHANGELOG.md, Commands/Admin/ClearTenantAppCatalogUrl.cs, Commands/Admin/GetTenantAppCatalogUrl.cs, Commands/Admin/SetTenantAppCatalogUrl.cs, Commands/SharePointPnP.PowerShell.Commands.csproj
N/A
Added new commands `Clear-PnPTenantAppCatalogUrl` and `Set-PnPTenantAppCatalogUrl` introduced with [the January 2020 CSOM release](https://developer.microsoft.com/en-us/sharepoint/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-january-2020/).
Not all SPO WFEs have been updated yet to support these new CSOM commands, so for the time being it may still throw an exception that the commands are unknown. Should be solved automatically once the servers are updated.
=> Added Clear-PnPTenantAppCatalogUrl and Set-PnPTenantAppCatalogUrl

CHANGELOG.md, Commands/Fields/AddField.cs
N/A
Remove FieldOptions from `Add-PnPField` as it was obsolete since 2015 already and caused confusion as it didn't do anything anymore as opposed to the `-Values` argument in `Set-PnPField` which does allow setting properties. Did some code cleanup and sanitation while being at it.
=> Removed obsolete field options from Add-PnPField

CHANGELOG.md, Commands/Base/BasePSCmdlet.cs
Reported in several issues, such as issue #2123
Fixing newtonsoft assembly resolving not working in Azure Functions. Tried all kinds of approaches, but no single approach I could find would work for when it would be locally installed on a machine, when it would be imported through import-module from a network share and in an Azure Function. Therefore added a simple File.Exists check if it the newtonsoft DLL can be found through its assembly location reference. If so (everything but an Azure Function), load it from there. If not (Azure Function), load it from the CodeBase path as it was being done before. Tested on all three scenarios and its working fine now.
=> Fixing newtonsoft assembly resolving not working in Azure Functions

CHANGELOG.md, Commands/Files/GetFile.cs
Issue #1854 
Added fallback in case the creator or person having last modified the file no longer exists in the environment such that the file can still be downloaded.
=> Bugfix in Get-PnPFile when user no longer exists

CHANGELOG.md, Commands/Graph/GetUnifiedGroup.cs
Depends on https://github.com/pnp/PnP-Sites-Core/pull/2614 to be merged first.
Added IncludeHasTeam to Get-PnPUnifiedGroup to allow checking for a Team provisioned for an Office 365 Group. Depends on https://github.com/pnp/PnP-Sites-Core/pull/2614 to be merged first.
=> Added IncludeHasTeam to Get-PnPUnifiedGroup

CHANGELOG.md, Commands/Utilities/BrowserHelper.cs
N/A
Changed using `Connect-PnPOnline -PnPO365ManagementShell` only working if your default system language is English. This is done by no longer looking at the language specific text on the page indicating the logon has been successful, but looking at the URL it redirects to after a successful login instead.
=> Connect-PnPOnline -PnPO365ManagementShell is no longer language specific

CHANGELOG.md, Commands/Web/GetWeb.cs, Commands/Web/SetWeb.cs
N/A
Added following arguments to `Set-PnPWeb` allowing them to be set: `CommentsOnSitePagesDisabled`, `DisablePowerAutomate`, `MegaMenuEnabled`, `MembersCanShare`, `NavAudienceTargetingEnabled`, `QuickLaunchEnabled`
Did some minor cleanup in Get-PnPWeb.
=> Added additional arguments to Set-PnPWeb

CHANGELOG.md, Commands/SharePointPnP.PowerShell.Commands.csproj, Commands/Site/DisableSharingForNonOwnersOfSite.cs, Commands/Site/GetSharingForNonOwnersOfSite.cs
Issue #2640 
Added `Get-PnPSharingForNonOwnersOfSite` and `Disable-PnPSharingForNonOwnersOfSite` to allow retrieval of the current state of being able to share the site and its items by only owners or also by its members. This is to accommodate issue #2640. It was not possible to add the current status to Get-PnPSite as requested due to the design of the SharePoint CSOM command. Therefore introduced two new commands. Unfortunately at this point there is no API yet to allow enabling the sharing again, thus there is no Enable-PnPSharingForNonOwnersOfSite.
=> Added Get-PnPSharingForNonOwnersOfSite and Disable-PnPSharingForNonOwnersOfSite 

CHANGELOG.md, Commands/SharePointPnP.PowerShell.Commands.csproj, Commands/Site/GetIsSiteAliasAvailable.cs
Requested through https://github.com/pnp/PnP-PowerShell/issues/2695
Adding `Get-PnPIsSiteAliasAvailable` to allow for checking if a certain alias is available to be used to create a new site collection with.
Depends on PnP Sites Core PR https://github.com/pnp/PnP-Sites-Core/pull/2657 to be merged first.
=> Adding Get-PnPIsSiteAliasAvailable to check if alias is available

CHANGELOG.md, Commands/Base/DisconnectOnline.cs, Commands/Base/PnPConnectionHelper.cs
Could play a role in some degree to https://github.com/pnp/PnP-PowerShell/issues/2752
In `Disconnect-PnPOnline -Connection $variable`, if having connected using `$variable = Connect-PnPOnline -CertificatePath -ReturnConnection`, it would not clean up the certificate on that connection instance, but instead try to do it on the current connection context. That has been fixed in this PR.
=> Fixed issue with Disconnect-PnPOnline not cleaning up certificate

CHANGELOG.md, Commands/Base/DisconnectOnline.cs, Commands/Base/PnPConnection.cs, Commands/Base/PnPConnectionHelper.cs
Discussed in https://github.com/pnp/PnP-PowerShell/issues/2752
Change to only remove the certificate from the MachineKeys on Disconnect-PnPOnline if the -CertificatePath has been used to connect as it seems to be causing weird side effects to some where it invalidates the private key.
-- PR on hold awaiting confirmation of test discussed in the issue thread --
=> Change to the removal of the certificate from the MachineKeys on Disconnect-PnPOnline 

Commands/Diagnostic/MeasurePnPList.cs
=>  Measure-PnPList: add list view threshold note

Commands/Base/ConnectOnline.cs, Commands/Base/PnPConnectionHelper.cs, Commands/Properties/Resources.Designer.cs, Commands/Properties/Resources.resx
N/A
Added verbose log to connect to show which parameter set a connect was matched with to aid in troubleshooting, added check when connecting using thumbprint, if the thumbprint resolves to the private key certificate and throw a clear warning if it resolves only to the public key certificate. Also updated documentation on the connect with thumbprint option that it requires the private key instead of the public key.
=> Added check when connecting using a thumbprint that the private key certificate is available

ModuleFilesGenerator/HelpFileGenerator.cs
N/A
OutputTypeLinks specified in the CmdletHelp attribute will now be added to the RelatedLinks sections of Get-Help
=> Added OutputTypeLinks specified in the CmdletHelp to Get-Help output

Commands/Admin/AddMicrosoft365GroupToSite.cs, Commands/Admin/AddOffice365GroupToSite.cs, Commands/SharePointPnP.PowerShell.Commands.csproj
N/A
Renamed to comply with Office 365 Group -> Microsoft 365 Group name change. Added alias to old cmdlet name for backwards compatibility.
=> Renamed Add-PnPOffice365GroupToSite to Add-Microsoft365GroupToSite

Commands/Files/CopyFile.cs
Relates to changes done through PR https://github.com/pnp/PnP-PowerShell/pull/2749
Making `Copy-PnPFile` across site collections available only to SharePoint Online as on-premises versions don't have the required API for it. Should solve build issues in on-premises Dev branch.
=> Making Copy-PnPFile across site collections available only to SharePoint Online

CHANGELOG.md, Commands/Principals/GetUser.cs
Relates to changes done through PR https://github.com/pnp/PnP-PowerShell/pull/2754
Made `Get-PnPUser -WithRightsAssignedDetailed` addition available to SharePoint Online only as the on-premises CSOM doesn't support a required property for this to work. Should fix on-premises builds in the Dev branch.
=> Made Get-PnPUser -WithRightsAssignedDetailed addition available to SharePoint Online only

Commands/Provisioning/Site/ReadProvisioningTemplate.cs
None
Currently a NullDereference exception is thrown if ```Add-PnPListFoldersToProvisioningTemplate``` is called with a path that doesn't exist:
This PR handles the cases by throwing a FileNotFoundException with the path of the file:
Steps to reproduce the issue:
```powershell
Connect-PnPOnline "https://<tenant>.sharepoint.com/sites/<site>"
Add-PnPListFoldersToProvisioningTemplate -Path "SiteTemplate.pnp" -List "List name" -Recursive
```
=> Improve exception message when a provisioning template cannot be loaded from a file

Commands/Web/SetRequestAccessEmails.cs
No real issue, just some code cleanup
While working on a different issue I stumbled upon the comment left in https://github.com/pnp/PnP-PowerShell/commit/9b8643ac2c34495d2f8ee029d65fc9472c9fa1b5 and as https://github.com/pnp/PnP-Sites-Core/pull/2533 has been merged, PnP PowerShell can use the function defined in PnP-Sites-Core instead of having a copy of the same code
I tested ```Set-PnPRequestAccessEmails -Disabled:$false``` in a Team Site on SPO and it changed the setting correctly.
=> Set-PnPRequestAccessEmails cleanup

Samples/Connect.AzureAutomation/Deploy-AzureAppOnly.ps1, Samples/Connect.AzureAutomation/Deploy-AzureAutomation.ps1, Samples/Connect.AzureAutomation/Deploy-FullAutomation.ps1, Samples/Connect.AzureAutomation/Readme.md, Samples/Connect.AzureAutomation/test-connection-runbook.ps1
Sample scripts (4) for creating an Azure Automation account, Azure AD App, loading PnP PowerShell module and publishing a sample runbook connecting to SharePoint with App-Only certificate. This provides an example of how this can be setup securely.
I have provided more detail in the readme that accompanies the sample
=> Added sample for azure automation

Commands/Utilities/CertificateHelper.cs
Improves the troubleshooting of #2879
This PR improves the error messages displayed when a valid certificate cannot be loaded from the given path.
Handled cases:
1. The path is a folder (before it would say "Access to Path 'C:\Temp' is denied")
1. The path doesn't exist at all
1. The path is an empty file (before it would say "Array may not be empty or null")
* **Please target your PR to Dev branch. If you do not target the Dev branch we will …
=> Improve error messages when a valid certificate cannot be loaded from the given path

CHANGELOG.md, Commands/Web/GetSubwebs.cs
N/A
Several bugfixes in Get-PnPSubWebs, added optional -RootWeb parameter to allow inclusion of the rootweb in the results
=> Several fixes in Get-PnPSubWebs and addition of -RootWeb parameter

Commands/Fields/AddField.cs
Partially fixes https://github.com/pnp/PnP-PowerShell/issues/2535 . https://github.com/pnp/PnP-Sites-Core/pull/2754 in PnP-Sites-Core is required to be merged first.
Add new switch parameter "-AddToAllContentTypes" to Add-PnPField to automatically add the new field to all list content types.
ParameterSet_ADDFIELDTOLIST and ParameterSet_ADDFIELDBYXMLTOLIST are supported.
Example:
```powershell
Connect-PnPOnline $siteUrl
#create list with 3 content types
$list = New-PnPList -Title "AddToAllContentTypes" -Template GenericList
Set-PnPList -Identity $list -EnableContentType $true
Add-PnPContentType -Name "CT1"
Add-PnPContentType -Name "CT2"
Add-PnPContentType -Name "CT3"
Add-PnPContentTypeToList -List $list -ContentType "CT1"
Add-PnPContentTypeToList -List $list -ContentType "CT2" …
```
=> Add new switch parameter "-AddToAllContentTypes" to Add-PnPField to automatically add the new field to all list content types
