- Commands/OfficeDevPnP.PowerShell.Commands.csproj
- Commands/packages.config
This update requires that the PnP-Sites-Core repository is available at the same level as the PnP-PowerShell repository.
See https://github.com/OfficeDev/PnP-PowerShell/blob/dev/CONTRIBUTING.md
> Updated solution to reference/require PnP-Sites-Core

- Commands/Base/SetTraceLog.cs
- Documentation/SetSPOTraceLog.md
if no logfile is specified a console trace listener will be registered.
> Updated Set-SPOTraceLog to allow for console output

- Commands/Base/SPOnlineConnection.cs
Fix for #117 Support to urls with spaces in them
> Fix for #117

- Commands/Lists/RequestReIndexList.cs
- Commands/OfficeDevPnP.PowerShell.Commands.csproj
Small cmdlet to mark list for reindexing
> Added ReIndexList cmdlet

- Commands/DocumentSets/GetDocumentSetTemplate.cs
- Commands/Features/DisableFeature.cs
- Commands/Features/EnableFeature.cs
Enable-SPOFeature, Disable-SPOFeature & Get-SPODocumentSetTemplate
> Added some documentation

- Commands/OfficeDevPnP.PowerShell.Commands.csproj
- Commands/Site/GetAuditing.cs
- Commands/Site/SetAuditing.cs
Created a Get and Set Cmdlet for Auditing settings of the Site Collection
> Auditing settings

- Commands/Base/ConnectSPOnline.cs
- Commands/Base/SPOnlineConnectionHelper.cs
Browser-based login trough the WinForms WebBrowser control.
Requires [PR#257](https://github.com/OfficeDev/PnP-Sites-Core/pull/257) on PnP-Sites-Core
> Browser-based login

- Commands/Base/ConnectSPOnline.cs
- Commands/Base/GetAuthenticationRealm.cs
- Commands/Branding/AddNavigationNode.cs
- Commands/Branding/SetHomepage.cs
- Commands/Branding/SetMinimalDownloadStrategy.cs
- Commands/ContentTypes/AddContentType.cs
- Commands/ContentTypes/AddContentTypeToList.cs
- Commands/ContentTypes/AddFieldToContentType.cs
- Commands/ContentTypes/GetContentType.cs
- Commands/ContentTypes/SetDefaultContentTypeToList.cs
Updated documentation for Connect-SPOnline, Get-SPOAuthenticationRealm & Add-SPONavigationNode and bugfix for issue #214
> Updated documentation & bugfix for issue #214

- Commands/Lists/RemoveListItem.cs
- Documentation/RemoveSPOListItem.md
- Documentation/readme.md
Added Remove-SPOListItem cmdlet.
> Added Remove-SPOListItem cmdlet.

- Commands/UserProfiles/NewPersonalSite.cs
Updated the documentation for New-SPOPersonalSite
> Updated the documentation for New-SPOPersonalSite

- README.md
Added instructions on how to check the installed module version to the ReadMe.
> Instructions on how to check the installed version

- Commands/Principals/NewGroup.cs
- Commands/Principals/SetGroup.cs
Add help messages to New-SPOGroup en Set-SPOGroup based on [MSDN descriptions](https://msdn.microsoft.com/library/microsoft.sharepoint.client.group_members.aspx)
> Add help messages to New-SPOGroup en Set-SPOGroup

- Commands/ContentTypes/AddContentType.cs
- Commands/ContentTypes/AddContentTypeToList.cs
- Commands/ContentTypes/AddFieldToContentType.cs
- Commands/ContentTypes/RemoveContentType.cs
Documentation changes to Add-SPOContentType, Add-SPOContentTypeToList, Add-SPOFieldToContentType & Remove-SPOContentType
> Documentation changes

- Commands/Admin/GetTenantSite.cs
- Commands/Admin/GetTimeZoneId.cs
- Commands/Admin/GetWebTemplates.cs
- Commands/Admin/NewTenantSite.cs
- Commands/Admin/RemoveTenantSite.cs
- Commands/Admin/SetTenantSite.cs
- Commands/Apps/GetAppInstance.cs
- Commands/Apps/UninstallAppInstance.cs
- Commands/Base/ConnectSPOnline.cs
- Commands/Base/GetAuthenticationRealm.cs
- Commands/Base/GetAzureADManifestKeyCredentials.cs
- Commands/Base/GetHealthScore.cs
- Commands/Base/GetProperty.cs
- Commands/Branding/ConvertProvisioningTemplate.cs
- Commands/Branding/GetCustomAction.cs
- Commands/Branding/NewProvisioningTemplateFromFolder.cs
- Commands/Branding/RemoveCustomAction.cs
- Commands/Branding/SetMasterPage.cs
- Commands/Branding/SetMinimalDownloadStrategy.cs
- Commands/Branding/SetTheme.cs
Added and updated documentation for a set of CmdLets
> Add and updated documentation for these CmdLets

- Commands/Principals/SetGroupPermissions.cs
- Documentation/SetSPOGroupPermissions.md
> Manual merge of PR 313 due to namespace conflict

- Commands/Branding/ApplyProvisioningTemplate.cs
Fixed incorrect check for rooted ResourceFolder path when using a relative folder
> Fixed incorrect check for rooted ResourceFolder path

- Samples/Modules.Install/Install-SharePointPnPPowerShellHelperModule.ps1
> Rename function call

- Commands/Provider/SPOContentParameters.cs
- Commands/Provider/SPOContentReaderWriter.cs
- Commands/Provider/SPODriveInfo.cs
- Commands/Provider/SPODriveParameters.cs
- Commands/Provider/SPOProvider.cs
Just removed some unused code, and did some general code cleanup in the provider files.
> Provider cleanup

- Commands/Web/AddFile.cs
- Commands/Web/AddFolder.cs
- Commands/Web/AddIndexedProperty.cs
- Commands/Web/EnsureFolder.cs
- Commands/Web/FindFile.cs
- Commands/Web/GetFile.cs
- Commands/Web/GetFolderItem.cs
- Commands/Web/GetIndexedPropertyKeys.cs
- Commands/Web/GetMasterPage.cs
- Commands/Web/GetPropertyBag.cs
- Commands/Web/GetSubwebs.cs
- Commands/Web/GetWeb.cs
- Commands/Web/InvokeWebAction.cs
- Commands/Web/NewWeb.cs
- Commands/Web/RemoveFile.cs
- Commands/Web/RemoveFolder.cs
- Commands/Web/RemovePropertyBagValue.cs
- Commands/Web/RemoveWeb.cs
- Commands/Web/RemovedIndexedProperty.cs
- Commands/Web/RequestReIndexWeb.cs
- Commands/Web/SetFileCheckedIn.cs
- Commands/Web/SetFileCheckedOut.cs
- Commands/Web/SetIndexedProperties.cs
- Commands/Web/SetPropertyBagValue.cs
- Commands/Web/SetWeb.cs
Hi Erwin
Hopefully this is now just the Remove-SPOFolder change.
Regards
Nigel
> Added Remove-SPOFolder

- Commands/DocumentSets/RemoveContentTypeFromDocumentSet.cs
- Documentation/RemoveSPOContentTypeFromDocumentSet.md
Fix for Issue #327 
-> Renamed class
-> Fixed Example 3
> Fixed Typo in Cmdlet as described in Issue "Typo in Example 3 #327"

- Commands/DocumentSets/SetDocumentSetField.cs
__Example 1:__
Set**As**SharedField -> SetSharedField
Set**As**WelcomePageField -> SetWelcomePageField
__Example 2:__
Remove**As**SharedField -> RemoveSharedField
Remove**As**WelcomePageField -> RemoveWelcomePageField
> Fixed parameter names in Set-SPODocumentSetField samples.

- Commands/Lists/SetListItem.cs
Added sample value settings for all column types based on @Pieter-Veenstra post at https://veenstra.me.uk/2016/06/13/office-365-sharepoint-update-list-items-using-powershell/
> Added detailed information on different values to be set. Ref Issue #366

- Commands/Web/SetWeb.cs
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    |  yes
| New sample?      | no
| Related issues?  | 
Added options to set Description, MasterUrl and CustomMasterUrl to a Web with the Set-SPOWeb commandlet.
> Added options to set Description, MasterUrl and CustomMasterUrl to a Web

- README.md
Trivial change but up-to-date webcast needs a link ;-)
> Added link to latest PnP webcast.

- Commands/Base/GetAzureADManifestKeyCredentials.cs
- Commands/Base/SetTraceLog.cs
- Commands/Branding/AddCustomAction.cs
- Commands/Branding/AddJavaScriptBlock.cs
- Commands/Branding/SetMasterPage.cs
- Commands/DocumentSets/SetDocumentSetField.cs
- Commands/Extensibility/NewExtensibilityHandlerObject.cs
- Commands/Lists/SetDefaultColumnValues.cs
- Commands/Principals/NewUser.cs
- Commands/Publishing/AddHtmlPublishingPageLayout.cs
- Commands/Search/GetSiteSearchQueryResults.cs
- Commands/Search/SetSearchConfiguration.cs
- Commands/Site/SetAppSideLoading.cs
- Commands/Taxonomy/ImportTaxonomy.cs
- Commands/Web/EnsureFolder.cs
- Commands/Web/GetMasterPage.cs
- Commands/Web/InvokeWebAction.cs
- Commands/Web/NewWeb.cs
- Commands/Web/RemovedIndexedProperty.cs
- Commands/Web/SetIndexedProperties.cs
- Commands/WebParts/GetWebPart.cs
- Commands/Workflows/AddWorkflowDefinition.cs
- Commands/Workflows/RemoveWorkflowDefinition.cs
These are fairly small documentation changes and fixes so didn't bother to run regression tests, but did check that it still compiles so should be okay ;-)
> Fixed assorted typos.

- Commands/Lists/GetListItem.cs
Adds new `PageSize` parameter to `Get-SPOListItem` to allow paging through large lists.
> Add paging support to Get-SPOListItem

- Commands/Web/AddFile.cs
Added CheckInComment parameter
Added Values parameter to set item properties after upload #163 
Fixed to use ApproveComment instead of PublishComment when calling ApproveFile
> AddFile changes

- Commands/Principals/NewGroup.cs
OnlyAllowMembersViewMembership is true by default and therefore we add a
switchparameter to disallow members to view membership.
> Added DisallowMembersViewMembership

- Commands/Base/ConnectSPOnline.cs
Bug Fix
Fixes #505
Added a check for credentials null when the UseAdfs switch is used.
> Fixed support for Credentials parameter when using ADFS with Connect-SPOnline

- Tests/PSTestScope.cs
> Fixed incorrect reference to connect-sponline

- Commands/Provisioning/NewProvisioningTemplateFromFolder.cs
- Commands/Workflows/RemoveWorkflowSubscription.cs
- Documentation/NewPnPProvisioningTemplateFromFolder.md
- Documentation/RemovePnPWorkflowSubscription.md
- Documentation/readme.md
> Fixed incorrect ref to SPO

- Commands/Lists/SetListItem.cs
> Allow Set-PnPListItem to update only the content type

- Commands/Lists/SetDefaultColumnValues.cs
> Fixes issue with setting default column values for fields of type MultiChoice

- Commands/Admin/SetTenantSite.cs
- Documentation/SetPnPTenantSite.md
> Updated example

- Commands/Branding/SetTheme.cs
- Documentation/SetPnPTheme.md
- changelog.md
> Added parameters to Set-PnPTheme

- Commands/Base/ExecuteQuery.cs
- Commands/ContentTypes/GetContentType.cs
- Commands/Events/GetEventReceiver.cs
- Commands/Features/DisableFeature.cs
- Commands/Features/EnableFeature.cs
- Commands/Fields/AddField.cs
- Commands/Fields/AddFieldFromXml.cs
- Commands/Fields/AddTaxonomyField.cs
- Commands/Files/AddFile.cs
- Commands/Files/AddFolder.cs
- Commands/Files/EnsureFolder.cs
- Commands/Files/GetFile.cs
- Commands/Principals/AddUserToGroup.cs
- Commands/Publishing/AddMasterPage.cs
- Commands/Search/GetSearchConfiguration.cs
- Commands/Taxonomy/ExportTaxonomy.cs
- Commands/Taxonomy/ExportTermGroupToXml.cs
- Commands/Web/GetPropertyBag.cs
- Commands/Web/GetSubwebs.cs
- Commands/WebParts/GetWebPartProperty.cs
Fixed a few typos, updated some documentation examples.
> Small documentation update

- Commands/Graph/NewUnifiedGroup.cs
- Commands/Graph/SetUnifiedGroup.cs
- Documentation/NewPnPUnifiedGroup.md
> Updated New-PnPUnifiedGroup and Set-PnPUnifiedGroup

- Commands/Graph/NewUnifiedGroup.cs
> Fixed behavior of CreateUnifiedGroup.

- Commands/Lists/GetListItem.cs
- [ x] Improvement
Add output warning messages if you are combining parameters which does not work together.
> Output warnings for unsupported parameter combinations for Get-PNPListItem

- Commands/Taxonomy/SetTaxonomyFieldValue.cs
Fixes #465  
Just extends the CMDlet to set multiple terms in a field. The functionality was already implemented in the PnP Site Core library.
> Added functionality to set multiple terms into field.

- Commands/Publishing/SetDefaultPageLayout.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
- Documentation/SetPnPDefaultPageLayout.md
- Tests/BrandingTests.cs
- [X ] New Feature
No issues related.
New PowerShell cmdlet: Set-PnPDefaultPageLayout
Sets a default page layout
> New cmdlet Set-PnPDefaultPageLayout

- Commands/Admin/NewTenantSite.cs
- Commands/ContentTypes/RemoveContentType.cs
- Commands/DocumentSets/RemoveContentTypeFromDocumentSet.cs
- Commands/Fields/RemoveField.cs
- Commands/Files/RemoveFile.cs
- Commands/Files/RemoveFolder.cs
- Commands/Files/SetFileCheckedIn.cs
- Commands/Files/SetFileCheckedOut.cs
- Commands/Lists/NewList.cs
- Commands/Lists/RemoveList.cs
- Commands/Principals/NewUser.cs
- Commands/Principals/RemoveGroup.cs
- Commands/Principals/RemoveUserFromGroup.cs
- Commands/Taxonomy/ImportTaxonomy.cs
- Commands/Taxonomy/NewTermGroup.cs
- Commands/UserProfiles/NewPersonalSite.cs
- Commands/Utilities/SendMail.cs
- Commands/Web/AddIndexedProperty.cs
- Commands/Web/NewWeb.cs
- Commands/Web/RemovePropertyBagValue.cs
- Commands/Web/RemovedIndexedProperty.cs
Add some additional documentation and examples.
Also, New-PnPTermGroup threw an error (format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.), added a ClientContext.ExecuteQueryRetry()
> Add some additional documentation and examples

- Commands/Files/MoveFolder.cs
- Commands/Files/RenameFolder.cs
As requested in #609 
Initial commit for a Rename-PnPFolder cmdlet
> Added Rename-PnPFolder and Move-PnPFolder cmdlets

- Commands/Publishing/AddPublishingImageRendition.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
- Documentation/AddPnPPublishingImageRendition.md
- Documentation/readme.md
Dependent upon Core pull request number 910 - **https://github.com/SharePoint/PnP-Sites-Core/pull/910**
Added cmdlet Add-PnPPublishingImageRendition to allow adding new, uniquely-named image renditions to SharePoint.
> Pnp ps publishingimagerenditions

- Commands/Lists/SetList.cs
- Commands/Principals/SetGroup.cs
- [ X] Bug Fix
Fixes #591 
Small change to check if EnableContentTypes has been provided as a parameter. Only if this is the case will the list setting be updated
> Fix for issue #591

- Commands/Lists/GetListItem.cs
- [x ] Bug Fix
Removed T from TThe in help message
> Removed T from TThe

- Commands/Lists/AddListItem.cs
- Commands/Lists/SetListItem.cs
- Commands/Provisioning/ApplyProvisioningTemplate.cs
- Commands/Provisioning/ConvertProvisioningTemplate.cs
- Commands/Provisioning/GetProvisioningTemplate.cs
- Documentation/AddPnPListItem.md
- Documentation/ConvertPnPProvisioningTemplate.md
- Documentation/SetPnPListItem.md
- Documentation/readme.md
> Updated AddListItem and SetListItem to handle Taxonomy fields

- Commands/Search/GetSiteSearchQueryResults.cs
- [ x] New Feature
Added option to automatically page beyond 500 results in order to get absolutely all sites.
Added range check on MaxResults parameter.
Added parameter sets as MaxResults and StartRow is not applicable for -All
> Added -All switch to get more than 500 in one go

- Commands/InformationManagement/ClosureState.cs
- Commands/InformationManagement/GetSiteClosure.cs
- Commands/InformationManagement/SetSiteClosure.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
Dependent on #959
Added commandlet to open/close a site which has a site policy applied to it
> Added Set-PnPSiteClosure cmdlet

- Commands/Search/PnPResultTable.cs
- Commands/Search/PnPResultTableCollection.cs
- Commands/Search/SubmitSearchQuery.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
A general purpose commandlet to execute search queries with - supporting all options on the KeywordQuery object as well as adding an -All switch to auto page all results.
> Added Submit-PnPSearchQuery commandlet

- Commands/Lists/SetListItem.cs
Added support to set multiple lookup values if field support it. Values you can be set as a string with comma or semicolon separator, or as an int/string array with id's.
> Add support for multi lookup on Set-PnPListItem

- Commands/Publishing/AddPublishingPage.cs
Should resolve issue: #663 
Set Folder parameter to not be required.
> Folder path not required

- Commands/Lists/SetDefaultColumnValues.cs
Support setting a default taxonomy field value for a library based on term id instead of full label path.
> Add support to set default column value based on term id

- Commands/Apps/GetAppInstance.cs
- Commands/Apps/UninstallAppInstance.cs
- Commands/Base/PipeBinds/AppPipeBind.cs
Enables user to specify App Title when using the Get-PnPAppInstance or Uninstall-PnPAppInstance. works by extending the AppPipeBind.
The code to resolve the AppInstance by Title isn't ideal, it pulls the entire set of apps down then filters them out, but it's much easier on the user.
> Updated AppPipeBind and Cmdlets to implement.

- Commands/Lists/GetListItem.cs
Fixes #665 
Introduced ScriptBlock argument: the script block that will run after every page request is executed and results are written to output
> Get-PnPListItem callback to execute after each page request

- Commands/Provider/SPODriveInfo.cs
- Commands/Provider/SPOProvider.cs
- [x ] Bug Fix
Fix for Move-Item that allowed move into self, which results in the item being deleted.
Also some small improvements in the cache handling in the provider.
> Provider Fixes

- Commands/Lists/SetDefaultColumnValues.cs
Allow setting default column values for picture libraries (109)
> Allow default metadata on picture libraries

- Commands/Provider/SPOProvider.cs
Build error introduced in PR #744 
Fix for not being able to build solution for SP13
> Fix for provider not building for SP13

- Commands/Lists/SetListItem.cs
#674
Fixes issue if you pass in int array.
> Bugfix on multi-lookup related to #674

- Commands/Lists/SetDefaultColumnValues.cs
Relates to https://github.com/SharePoint/PnP-Sites-Core/pull/1092
Support to set default values for people columns using the id and ident of a user from the user information list.
> Support setting default column values for people fields.

- Commands/Search/SubmitSearchQuery.cs
Fix for not assigning properties not specified, as it breaks the call.
> Fix for not assigning non-set values.

- README.md
--
Small punctuation fixes in readme
> Small punctuation fixes in readme

- Commands/Graph/SetUnifiedGroup.cs
Dependent on #1072
Add functionality to add owners and members to an existing group.
Add function to change a groups visibility from public to private or vice versa.
> Added ability to change owners/members/visibility of a group

- Commands/Lists/SetDefaultColumnValues.cs
Requires Core code from: https://github.com/SharePoint/PnP-Sites-Core/pull/1100
Added support for more field types of default columns: Boolean, DateTime, Number, Currency
> Support Boolean, DateTime, Number, Currency

- Commands/Base/ConnectOnline.cs
None
Typo fix on Connect-PnPOnline example
> fixed typo, changed clientsecret to appsecret

- Commands/Search/SubmitSearchQuery.cs
Added new switch parameter -RelevantResults to Submit-PnPSearchQuery cmdlet, when specified cmdlet will only return relevant results (if any) in form of PSObject collection, so you can immediately execute select, sort etc.
> RelevantResults switch for Submit-PnPSearchQuery

- Commands/Search/SubmitSearchQuery.cs
- Documentation/SubmitPnPSearchQuery.md
> Fixed examples

- Commands/Lists/SetListItem.cs
- Documentation/SetPnPListItem.md
Fixes #784 
Code now correctly setting value for a single taxonomy/metadata value
> Single Term Saves on Set-PnpListItem issue #784

- Commands/Properties/AssemblyInfo.cs
> May 2017 Release

- Commands/Base/PipeBinds/UserPipeBind.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
- Commands/Web/GetUser.cs
- Tests/WebTests.cs
New cmdlet Get-PnPUser to enumerate web SiteUsers or get user by LoginName/Id
> Get-PnPUser

- Commands/Lists/SetListItem.cs
If you pass in **null** to a field, that value will be set, meaning you clear the field. This was not working on People/Lookup/Taxonomy.
> Added support to clear values - if you pass in null to Set-PnPListItem

- Commands/Properties/AssemblyInfo.cs
- Documentation/GetPnPUnifiedGroup.md
Intermediate release to fix issue with incorrect CSOM library
> June Intermediate Release 1

- Commands/Lists/RemoveList.cs
> Fixed help

- Samples/Tenant.Migration/Documentation/readme.md
- Samples/Tenant.Migration/readme.md
- [X ] Bug Fix
Small typos in the readme file
> Fixed some small typos in the readme file.

- Commands/RecycleBin/ClearRecycleBinItem.cs
…cleBinItem already ensures the item is loaded from the context.
N/A
Removed a redudant retrieval of the recyclebin item. Identity.GetRecycleBinItem already ensures the item is loaded from the context.
> Optimized Clear-PnPRecycleBinItem

- Commands/Base/PnPWebRetrievalsCmdlet.cs
N/A
Added class comment to PnPWebRetrievalsCmdlet to clarify its intended purpose. Removed unused usings.
> Added PnPWebRetrievalsCmdlet inline code comment

- Commands/Lists/SetView.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
- Documentation/SetPnPView.md
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/983
Added Set-PnPView which allows setting parameters of Views
> Added Set-PnPView command

- Commands/SharePointPnP.PowerShell.Commands.csproj
- Commands/Site/AddSiteCollectionAdmin.cs
- Commands/Site/GetSiteCollectionAdmin.cs
- Commands/Site/RemoveSiteCollectionAdmin.cs
- Documentation/AddPnPSiteCollectionAdmin.md
- Documentation/GetPnPSiteCollectionAdmin.md
- Documentation/RemovePnPSiteCollectionAdmin.md
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/977
Added Add-PnpSiteCollectionAdmin, Get-PnPSiteCollectionAdmin and Remove-PnPSiteCollectionAdmin commands
> Add pn p site collection admin2

- Commands/Admin/SetTenantSite.cs
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/975
Updated documentation to clarify sitecol owners get added to the existing ones. The existing ones do not get replaced.
> Updated Set-PnPTenantSite -Owners documentation

- Commands/Principals/RemoveUser.cs
- Commands/Properties/Resources.Designer.cs
- Commands/Properties/Resources.resx
- Commands/SharePointPnP.PowerShell.Commands.csproj
- Documentation/RemovePnPUser.md
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/968
Added Remove-PnPUser command which allows removal of an user from the User Information List
> Added Remove-PnPUser

- Commands/Principals/GetUser.cs
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/967
Added samples and documentation on Get-PnPUSer
> Added samples and documentation on Get-PnPUSer

- Commands/Fields/SetField.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
Resubmit of https://github.com/SharePoint/PnP-PowerShell/pull/965
Adding Set-PnPField command which allows setting field properties
> Adding Set-PnPField

- Commands/Base/ConnectOnline.cs
Added support to use the SPO Management Shell ADAL app as login.
Also fixed a bug where ADAL login failed if the cache dir was not there - now it ensures the folder first.
> Added support to login using the SPO Management Shell ADAL application.

- Commands/Base/GetStoredCredential.cs
CmdletExamples updated. Get-SPOnlineStoredCredential labels replaced by Get-PnPStoredCredential labels.
GetStoredCredential.cs CmdletExamples updated. Get-SPOnlineStoredCredential labels replaced by Get-PnPStoredCredential labels.
> GetStoredCredential.cs CmdletExamples updated.

- Commands/Branding/GetCustomAction.cs
- Commands/Branding/GetJavaScriptLink.cs
Resubmit of
Added optional argument to throw exception if retrieved item not found by Get-PnPCustomAction and Get-PnPJavaScriptLink
> Added optional exception if Get-PnPCustomAction and Get-PnPJavaScriptLink yield no result

- Commands/Admin/GetTenantSite.cs
https://github.com/SharePoint/PnP-PowerShell/issues/676
No filter will be used in case no filter variables are provided. This returns way more results. Went from 1400-something to 18000-something on a tenant where I tested this against. Added support for iterating through multiple batches of results. The Detailed flag was ignored when a filter was used, fixed that. Fixed inconsistent naming of OneDrive 4 Business to OneDrive for Business in help text, made period use in help text consistent.
> Various fixes in Get-PnPTenantSite

- Commands/Base/PnPWebCmdlet.cs
https://github.com/SharePoint/PnP-PowerShell/issues/1061
Clarified how the Web argument should be used as the current HelpMessage didn't provide enough guidance and it was causing confusion.
> Clarified how the Web argument should be used in PnPWebCmdlet

- Samples/Provisioning.CreateSitesFromCsv/CreateSites.csv
- Samples/Provisioning.CreateSitesFromCsv/CreateSites.ps1
- Samples/Provisioning.CreateSitesFromCsv/README.md
I refactored the sample I added previous month. It shows how SharePoint sites hierarchy can be created from csv template.
Storing credentials in a txt file **removed** . Windows Credentials Manager used instead.
> Refactored: sample script that creates site collections and/or sub webs from CSV configuration file.

- Commands/Branding/AddCustomAction.cs
Added scope as a valid parameter for ClientSideComponentId custom actions. If not they end up web scoped. Issue for application customizers.
> Added scope as a valid parameter for ClientSideComponentId

- Commands/RecordsManagement/SetInPlaceRecordsManagement.cs
- Commands/Search/SetSearchConfiguration.cs
- Commands/Site/AddSiteCollectionAdmin.cs
- Commands/Site/GetSite.cs
- Commands/Site/InstallSolution.cs
- Commands/Site/RemoveSiteCollectionAdmin.cs
- Commands/Site/SetAppSideLoading.cs
- Commands/Site/UninstallSolution.cs
- Commands/Taxonomy/ExportTaxonomy.cs
- Commands/Web/GetPropertyBag.cs
- Commands/Web/GetRequestAccessEmails.cs
- Commands/Web/GetSubwebs.cs
- Commands/Web/GetWeb.cs
- Commands/Web/InvokeWebAction.cs
- Commands/Web/NewWeb.cs
- Commands/Web/RemovedIndexedProperty.cs
- Commands/WebParts/AddWebPartToWebPartPage.cs
- Commands/WebParts/AddWebPartToWikiPage.cs
- Commands/WebParts/GetWebPart.cs
- Commands/WebParts/GetWebPartProperty.cs
- Commands/WebParts/RemoveWebPart.cs
- Commands/WebParts/SetWebPartProperty.cs
- Commands/Workflows/AddWorkflowSubscription.cs
- Commands/Workflows/GetWorkflowDefinition.cs
- Commands/Workflows/GetWorkflowSubscription.cs
- Commands/Workflows/RemoveWorkflowDefinition.cs
- Commands/Workflows/RemoveWorkflowSubscription.cs
- Commands/Workflows/ResumeWorkflowInstance.cs
- Commands/Workflows/StopWorkflowInstance.cs
- [ X] Sample
Updated documentation
Updated documentation for multiple cmdlets
> Updated documentation for these cmdlets

- Commands/Events/AddEventReceiver.cs
N/A
Updated documentation to clarify which EventTypes can be used, added a sample on adding a remote event receiver to the web, minor code cleanup and changed event receiver mentions to remote event receiver as this won't work for registering FTC event receivers on prem.
> Updated documentation on Add-PnPEventReceiver

- Commands/Files/GetFile.cs
- Documentation/Get-PnPFile.md
- changelog.md
> Added force parameter to overwrite file

- Commands/Files/AddFile.cs
> Added better field type parsing

- Commands/ClientSidePages/SetClientSidePage.cs
- Documentation/Set-PnPClientSidePage.md
Fixes issue as reported in #1145
> Fixed typo

- Commands/Files/AddFile.cs
- Commands/Lists/AddListItem.cs
- Commands/Lists/SetListItem.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
- Commands/Utilities/ListItemHelper.cs
- Documentation/Set-PnPListItem.md
- changelog.md
Fixed issues as reported in #1133
> List Item Handling updates

- Commands/Site/SetAuditing.cs
- Documentation/Set-PnPAuditing.md
Fixes issues mentioned in issue #1109
> fixed issues with enabling and disabling auditing

- Commands/Base/ConnectOnline.cs
> Fixed parameter set issue with hightrust

- Commands/Base/PipeBinds/UserCustomActionPipeBind.cs
- Commands/Branding/RemoveCustomAction.cs
- Commands/Branding/RemoveJavaScriptLink.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
Resubmit for https://github.com/SharePoint/PnP-PowerShell/pull/959 as it needed to be cleaned up.
Added UserCustomActionPipeBind to allow getting Get-PnPCustomAction and Get-PnPJavaScriptLink objects and piping them to Remove-PnPCustomAction and Remove-PnPJavaScriptLink
> Added UserCustomActionPipeBind

- Commands/Provisioning/AddFileToProvisioningTemplate.cs
- Commands/Provisioning/NewProvisioningTemplateFromFolder.cs
- Documentation/Add-PnPFileToProvisioningTemplate.md
Fixes cmdlet issue discovered while addressing issue https://github.com/SharePoint/PnP-Sites-Core/issues/1435.
> Fixes issue with Add-PnPFileToProvisioningTemplate

- Documentation/Get-PnPApp.md
Reverts SharePoint/PnP-PowerShell#1243
> Revert "Update command name"

- Commands/Admin/NewSite.cs
- Documentation/New-PnPSite.md
> Fixed parameterset issue

- Commands/Provisioning/GetProvisioningTemplate.cs
Added support for schema v201801
> Added support for schema v201801

- Samples/Provisioning.CreateSitesFromCsv/CreateSites.ps1
Fixed comment typo from confuguration to configuration.
> Fixed typo.

- Samples/Provisioning.CreateSitesFromCsv/CreateSites.ps1
Reverts SharePoint/PnP-PowerShell#1299. Unfortunately, we do NOT take submissions to master directly in this repository, so we can't process this as such.
> Revert "Fixed typo."

- Commands/Taxonomy/GetTerm.cs
Get-PnPTerm currently fetches root terms only by a label in a term set. I added a switch `-Recursive` to allow finding the first term matching a label regardless of root or child term using `LabelMatchInformation` to find the term.
* Fixed sample messages which were wrong
* Removed unused using statement
> Added ability to look up term recursively from the label

- Commands/Lists/NewList.cs
- Commands/Lists/SetList.cs
- Documentation/New-PnPList.md
- Documentation/Set-PnPList.md
- Tests/ListsTests.cs
N/A
I'd like the ability to create or update lists to hidden from the SharePoint UI. This PR is supported by PnP-Sites-Core PR #1480.
> Support ability to create new hidden lists

- Documentation/Set-PnPClientSideWebPart.md
Changed Get-PnPClientSideWebPart to Get-PnPClientSideComponent as there yet is no cmdlet for Get-PnPClientSideWebPart.
> Minor documentation update for Set-PnPClientSideWebPart

- Commands/Diagnostic/MeasurePnPList.cs
- Commands/Diagnostic/MeasurePnPWeb.cs
- Commands/Diagnostic/MeasureResponseTime.cs
- Commands/Diagnostic/MeasureResponseTimeMode.cs
- Commands/Diagnostic/ResponseTimeStatistics.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
More documentation and samples for Diagnostics cmdlets and enhancements for Measure-PnPResponseTime, now can measure in 3 differents modes.
> Measure response time enhancement and documentation

- Commands/Lists/SetList.cs
- Documentation/Set-PnPList.md
- [ X ] New Feature
-
Added EnableAttachment prop for Set-PnPList.
> Added EnableAttachment prop for Set-PnPList

- Commands/Admin/GetTenantSite.cs
Implemented proper paging logic, as the previous one was broken when using the filter API.
Obsoleted a couple of params as they are no longer in use/needed.
> Fix for paging on fetching over ~1400 sites

- Commands/Utilities/ListItemHelper.cs
Occurs when trying to set multiple lookup values/taxonomy fields caused by EnsureProperties call while updating item.
> Fixes issue as mentioned in #1339 

- Commands/Base/ConnectOnline.cs
- Commands/Base/SPOnlineConnectionHelper.cs
- [X ] New Feature
Add a new parameter set to allow supplying a `X509Certifcate2` directly, and add all the common parameters to both parameter sets.
> Connect-PnPOnline: add additional HighTrustCertificate parameters

- CHANGELOG.md
- Commands/Base/PipeBinds/UnifiedGroupPipeBind.cs
- Commands/Graph/GetUnifiedGroup.cs
- Commands/Graph/GetUnifiedGroupMembers.cs
- Commands/Graph/GetUnifiedGroupOwners.cs
- Commands/Graph/RemoveUnifiedGroup.cs
- Commands/Graph/SetUnifiedGroup.cs
> Updated pipebind handling

- Commands/Provisioning/ApplyProvisioningTemplate.cs
Add parameter for specifying if fields should be allowed to be provisioned in sub webs. [PR 1685](https://github.com/SharePoint/PnP-Sites-Core/pull/1685) in PnP-Sites-Core is required.
> Add option for provisioning fields to sub sites

- Commands/Admin/AddSiteCollectionAppCatalog.cs
- [ X] Bug Fix
Change cmdlet name from Add-PnPOffice365GroupToSite to Add-PnPSiteCollectionAppCatalog at example.
> Update cmdlet example at AddSiteCollectionAppCatalog

- CHANGELOG.md
- Commands/SharePointPnP.PowerShell.Commands.csproj
- Commands/UserProfiles/GetUPABulkImportStatus.cs
- Commands/UserProfiles/NewUPABulkImportJob.cs
Added cmdlets to submit bulk upload jobs as well as retrieve status on submitted jobs.
> Added UPA bulk upload cmdlets

- Commands/Taxonomy/NewTerm.cs
New term, set local properties fix. It was set to use SetCustomProperty, but this is wrong and adds the local properties into the 'Shared Properties' instead to the 'Local Properties'.
> New term SetLocalCustomProperty fix

- Commands/Properties/AssemblyInfo.cs
> April 2018 Intermediate Release

- Commands/Apps/AddApp.cs
Fix command Add-PnPApp to be able to publish app to site collection app catalog.
> Fix command Add-PnPApp

- CHANGELOG.md
- Commands/Fields/GetField.cs
> Added InSiteHierarchy

- Commands/Taxonomy/ImportTaxonomy.cs
> Updated help

- Commands/RecycleBin/ClearRecycleBinItem.cs
- Commands/RecycleBin/RestoreRecycleBinItem.cs
N/A
Two examples of using the RecycleBinItem commands were still mentioning RecycleBinItems (plural) while in the eventually implemented code they were reverted to RecycleBinItem (singular). Updates the samples to match the actual implementation
> Modified RecycleBinItems samples to RecycleBinItem

- Commands/Diagnostic/MeasurePnPWeb.cs
N/A
Fixed incorrect sample pointing to Measure-PnPList instead of Measure-PnPWeb and having a non correct explanation with it.
> Fixed incorrect sample on Measure-PnPWeb

- Commands/Site/SetSite.cs
This reverts commit 960c87d44a93af0b9b24c956406fd7a853c0dc17.
> Revert "Removing code sample from removed parameter"

- CONTRIBUTING.md
N/A
Adding mentioning the proper Visual Studio Solution file to be used as discussed via e-mail
> Adding mention of the proper SLN file to use

- Commands/SharePointPnP.PowerShell.Commands.csproj
> fixed typo in csproj

- Commands/Provisioning/Tenant/TestTenantTemplate.cs
Using the new PnPTenantTemplate instead of PnPProvisioningHierarchy
Documentation issue
Simple Documentation fix on the naming of the PnP Tenant Template vs Hierarchy
> Documentation Update for PnP Tenant Template

- CHANGELOG.md
- Commands/ClientSidePages/MoveClientSideComponent.cs
- Commands/ClientSidePages/SetClientSideWebPart.cs
- Commands/WebParts/AddClientSideWebPart.cs
- Commands/WebParts/AddWebPartToWebPartPage.cs
- Commands/WebParts/AddWebPartToWikiPage.cs
- Commands/WebParts/GetWebPart.cs
- Commands/WebParts/GetWebPartProperty.cs
- Commands/WebParts/GetWebPartXml.cs
- Commands/WebParts/RemoveWebPart.cs
- Commands/WebParts/SetWebPartProperty.cs
- Samples/Provisioning.ModernListLibraryWebPartsFromXlsx/ProvisionModernPagesAndWebParts.ps1
None
Updated "webpart" references in documentation to "web part."
> Documentationupdates

- Commands/Files/GetFolder.cs
- Commands/Files/GetFolderItem.cs
- Commands/Files/MoveFolder.cs
- Commands/Files/RemoveFolder.cs
- Commands/Files/RenameFolder.cs
- Commands/Web/GetPropertyBag.cs
- Commands/Web/RemovePropertyBagValue.cs
- Commands/Web/SetPropertyBagValue.cs
Fixes #1794 
Added resource Path API support for folders to handle special characters in SPO such as `#` and `%` in folder names
> Feature : added resourcePath API support for folders

- Commands/Files/AddFile.cs
- Commands/Files/GetFile.cs
- Commands/Files/MoveFile.cs
- Commands/Files/RemoveFile.cs
- Commands/Files/RenameFile.cs
- Commands/Publishing/RemoveWikiPage.cs
Fixes #1766 
Added Resource Path API support to handle special characters in SPO for files like `#` and `%`
> Feature: Added Resource Path API support for Files

- CHANGELOG.md
- Commands/Lists/ClearDefaultColumnValues.cs
- Commands/Lists/SetDefaultColumnValues.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
Fixes #1706
* Fixes encoding issues with folders
* Added cmdlet to clear default column values
> Default column value fix

- Commands/Principals/SetGroup.cs
Fixes #1690
This PR fixes the Set-PnPGroup description parameter not working correctly.
SharePoint stores the group description in the Site User Info list's Notes property. 
By using the code, we are handling that and updating the Notes property and also the group's description property correctly.
> Fix: Set-PnPGroup description not working correctly

- CHANGELOG.md
> include update on Set-PnPGroup

- CHANGELOG.md
- Commands/Admin/NewSite.cs
- Commands/Provisioning/Tenant/SaveTenantTemplate.cs
- PostBuild.ps1
> 2019 February Release

- Tests/ProvisioningTemplateTests.cs
This is a public method, but should be ok since it is a test
> typo: Validat -> Validate

- Commands/Provider/SPOProxy/SPOProxyCopyItem.cs
- Commands/Provider/SPOProxy/SPOProxyImplementation.cs
- Commands/Provider/SPOProxy/SPOProxyMoveItem.cs
The function is internal so this shouldn't be breaking
> typo: Imlementation -> Implementation

- Commands/ClientSidePages/AddClientSidePage.cs
N/A
The same example existed twice. Removed one of them.
> Removed double example in Add-PnPClientSidePage

- Commands/Base/PipeBinds/ImageRenditionPipeBind.cs
> fix: camelCase idorname parameter

- README.md
N/A
The list with Install-Module packages didn't show the new 2019 version yet. Added it.
> Added mention of SharePoint 2019

- Commands/Base/SPOnlineConnection.cs
- Commands/Branding/AddCustomAction.cs
N/A
Allowing ClientSideComponentId and ClientSideComponentProperties for deploying SPFx Extensions to SharePoint 2019
> Allowing ClientSideComponent in Add-PnPCustomAction for SharePoint 2019

- Commands/Web/AddIndexedProperty.cs
- Commands/Web/GetIndexedPropertyKeys.cs
- Commands/Web/RemovedIndexedProperty.cs
NA
Added support for getting, adding and removing indexed property bags for SharePoint lists
> Feature : Added indexed property bag support for lists

- Commands/Lists/AddListItem.cs
Update on Synopsis as recommended by Vesa.
Issue #2665
> Update on Synopsis Issue #2665

- Commands/RecycleBin/RestoreRecycleBinItem.cs
- [x ] Bug Fix
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2821
Fixes the 2nd example that had an error and did not work.
> Corrected 2nd example

- Commands/Site/SetSite.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2349
Extended Example 2 description source: https://social.technet.microsoft.com/wiki/contents/articles/39331.sharepoint-online-verifying-and-modifying-flows-policy-in-site-using-powershell.aspx
> Extended description of Example 2

- Commands/Graph/SetUnifiedGroup.cs
- [x ] Bug Fix
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2811
Corrected Example 5, the owners parameter actually replaces any existing value.
> Corrected Example 5

- Commands/Admin/NewSite.cs
- [ x] Bug Fix
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2809
Corrected LCID for Italian that is 1040
> Corrected LCID for Italian

- Commands/Site/SetSite.cs
- [x ] Bug Fix
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2348
https://github.com/SharePoint/PnP-PowerShell/issues/1810
Changed description for NewUrl.
> Changed description for NewUrl

- Commands/Site/GetSite.cs
- [ x] New Feature
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2346
Added an example for Includes parameter and also a link for a full list of possible properties
> Added an example for Includes parameter

- Commands/Provisioning/Site/GetProvisioningTemplate.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2338
Added link for Handlers Enum
> Added link for Handlers Enum

- Commands/Navigation/GetNavigationNode.cs
- [x ] Bug Fix
Related to https://github.com/MicrosoftDocs/office-docs-powershell/issues/2164
Example 3 lacked -Location and was using -TopNavigationBar instead
> Changed example 3

- Commands/Lists/SetView.cs
- [ x] New Feature
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2712
Added a link in the DetailedDescription to get more info about possible properties of a view.
> Added info about properties of a view

- Commands/Fields/AddField.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2823
Extended Type parameter description
> Extended Type parameter description

- Commands/Base/GetHealthScore.cs
- Commands/Files/CopyFile.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2640
Added more info about the origin and meaning of the health score value and some links to official documentation about it, to better understand how to determine the site's performance based on this value.
> Added more info about the meaning of the health score value and copy-PnPFile cmdlet

- Commands/Provisioning/Site/GetProvisioningTemplate.cs
> Added capability to export template with just selected lists

- Commands/ClientSidePages/ConvertToClientSidePage.cs
Related to https://github.com/SharePoint/sp-dev-modernization/issues/154
Added target connection option enables cross farm transformation also POC works on-premises
@jansenbe - this is the example code super simple but need to expand and limit some capability e.g. ListItemPermissions
> POC for on-prem to online conversion

- Commands/RecordsManagement/SetListItemAsRecord.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3492
Added a link to more information about Records Management
> Added a link to more information

- Commands/Provisioning/Site/ApplyProvisioningTemplate.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/523
Added link to Handlers Enum
> Added link to Handlers Enum

- Commands/Provisioning/Tenant/ApplyTenantTemplate.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3212
Extended cmdletHelp about required permissions to run this cmdlet
> Extended cmdletHelp about required permissions

- Commands/RecycleBin/RestoreTenantRecycleBinItem.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3684
The documentation inside this cmdlet said reset instead of restore in many places.
> Corrected reset to restore

- Commands/Site/AddRoleDefinition.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3655
Added link to PermissionKind enum
> Added link to PermissionKind enum

- Commands/Lists/SetListItem.cs
Fixes #2152 
Added systemUpdate support in SPO while setting content type value for list items
> Added systemUpdate support for list item content types

- Commands/Apps/GrantTenantServicePrincipalPermission.cs
Fixes #2159 
Added multi-lingual support for web API Permission list and additional null check for tenant app catalog site collection.
> Feature : Added multi-lingual support for webAPI Permission list

- Commands/Branding/AddJavaScriptLink.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3512
Added note that this functionality is only intended to work on Sharepoint Classic sites experience.
> Added note about classic sites

- Commands/Lists/SetList.cs
Fix for bug #2153 
- [ X ] Bug Fix
Set-PnPList - ResetRoleInheritance missing #2153
Update for Set-PnPList command
> Include ability to reset broken inheritance for list

- Commands/Site/SetSite.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3523
Corrected the example of the logofilepath that was using an incorrect parameter
> Corrected set logo example

- Commands/Principals/GetUser.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3916
Added enclosing quotes to the identity sample value so that [the documentation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpuser) is rendered with them, like example 4
> Example 3 to be enclosed in double quotes

- Commands/InformationManagement/GetLabel.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3909
A more detailed description is being proposed here, to clarify what type of label.
> Added clarification to description

- Commands/ClientSidePages/ExportClientSidePageMapping.cs
Part of related changes 
https://github.com/SharePoint/sp-dev-modernization/issues/286 
Please describe the changes in the PR.
Add logging to cmdlet for pnp transformation powershell 
@jansenbe looping you in - minor change, could be worth enabling by default?
> Added console logging to export to cmdlet

- Commands/Admin/NewSite.cs
- Commands/Admin/NewTenantSite.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3700
Proposing with this pull request to change some wording about what is being created to align to Sharepoint Admin center.
> Changing some wording about what is being created

- Commands/ClientSidePages/AddClientSidePage.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4011
An example is being added on how to create a Client Side Page under a folder
> Adding an example

- Commands/Branding/AddCustomAction.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4016
Added the need to run Install-PnpApp before this cmdlet when impacting a site.
> Added the need to run Install-PnpApp

- Commands/Base/GetContext.cs
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3226
Added a more descriptive example, this example was taken from SetContext
> Added a 2nd example

- Commands/Base/ConnectOnline.cs
N/A
Clarifying in the help text for Credentials where you have to store the credentials in the Windows Credential Manager to make it work
> Clarifying using Connect-PnPOnline using Credential Manager

- Commands/Apps/InstallApp.cs
Samples on Install-PnPApp were showing non existant command. Replaced by proper command.
> Fixing help text on Install-PnPApp

- Commands/ClientSidePages/ConvertToClientSidePage.cs
N/A
Fixed error in sample 10 where c:\temp would be rendered as c:<tab>emp
> Fixed error in sample 10 for ConvertTo-PnPClientSidePage

- Commands/Files/CopyFile.cs
- Tests/FilesTest.cs
Fixes #2195, Fixes #2296, Fixes  #1051
This PR adds some code changes to fix the following issues>
- Copy files with special characters
- Copy empty folders
- Copy files from one folder to another
This PR replaces #2240 .
> Several fixes & additional tests for Copy-PnPFile

- Commands/Admin/SetHubSite.cs
NA
This PR adds additional properties such as `HideNameInNavigation` and `RequiresJoinApproval` while setting hub site properties.
> Feature: added additional properties for Set-PnPHubSite

- Commands/Search/GetSearchCrawlLog.cs
> Minor Example Fix

- Commands/Provisioning/Site/AddDataRowsToProvisioningTemplate.cs
- Tests/ListDataRowProvisioningTemplate.cs
Fixes #2032 
Exporting as list of values delimited with ;#
Adding test as well.
> Exporting MultiChoice values in correct format

- Commands/Admin/RemoveSiteCollectionAppCatalog.cs
Fixes SharePoint/PnP-PowerShell#2377
Edit the sample Cmdlet
> fix: Remove-PnPSiteCollectionAppCatalog cmdlet example

- Commands/Base/ConnectOnline.cs
- Commands/Base/SPOnlineConnectionHelper.cs
> Merged PR605

- Commands/Graph/GetUnifiedGroupMembers.cs
- Commands/Graph/GetUnifiedGroupOwners.cs
N/A
Allow piping a Get-PnPUnifiedGroup to Get-PnPUnifiedGroupOwners and Get-PnPUnifiedGroupMembers
> Allow piping a Get-PnPUnifiedGroup to GroupOwners and GroupMembers

- Commands/Base/PipeBinds/UnifiedGroupPipeBind.cs
- Commands/Graph/GetUnifiedGroup.cs
- Commands/Graph/GetUnifiedGroupMembers.cs
- Commands/Graph/GetUnifiedGroupOwners.cs
- Commands/Graph/NewUnifiedGroup.cs
N/A
Code cleanup removing unused usings from all *-PnPUnifiedGroup* commands
> Cleanup removing unused usings from all *-PnPUnifiedGroup* commands

- Commands/InformationManagement/GetLabel.cs
- Commands/InformationManagement/ResetLabel.cs
- Commands/InformationManagement/SetLabel.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
Resubmit of PR #2233 with some small changes to it
> Resubmit of PR2233

- Commands/Base/GetHealthScore.cs
> Merged PR2004

- Commands/Admin/AddOrgNewsSite.cs
- Commands/Admin/GetOrgNewsSite.cs
- Commands/Admin/RemoveOrgNewsSite.cs
- Commands/Admin/SetOrgNewsSite.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
Resolved merge conflicts in PR #2060
> Merge of PR2060

- Commands/Branding/AddCustomAction.cs
N/A
Updating msdn links to docs.microsoft.com links as MSDN will be retired
> Updating msdn links to docs.microsoft.com links as MSDN will be retired

- Commands/Lists/AddListItem.cs
N/A
Updated old MSDN links in the *-ListItem commands to the new docs.microsoft.com links
> Updated old MSDN links in the *-ListItem commands

- Commands/Files/GetFolderItem.cs
Merge and resubmit of PR #2362
> Resubmit of PR2362

- Commands/Base/ConnectOnline.cs
- Commands/Base/SPOnlineConnectionHelper.cs
- Commands/Utilities/CertificateHelper.cs
- Commands/Web/SetWeb.cs
> Merged PR2201

- CHANGELOG.md
- Commands/Lists/AddView.cs
- Commands/Lists/SetView.cs
> Resubmit of PR2257

- Commands/Site/SetSite.cs
> Merged PR2328

- CHANGELOG.md
- Commands/Admin/ClearTenantAppCatalogUrl.cs
- Commands/Admin/GetTenantAppCatalogUrl.cs
- Commands/Admin/SetTenantAppCatalogUrl.cs
- Commands/Lists/NewList.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
> Resubmit of PR2481

- CHANGELOG.md
- Commands/Base/BasePSCmdlet.cs
> Resubmit of PR2490

- CHANGELOG.md
- Commands/Admin/RemoveTenantCdnOrigin.cs
> Resubmit of PR #2500 

- Commands/Lists/NewList.cs
None
Minor update to the sample showing the `-Url` parameter to make it more obvious that you are specifying the full URL for the new list
> Updated sample to add lists to URL

- CHANGELOG.md
- Commands/ClientSidePages/AddClientSidePage.cs
> Resubmit of PR2514

- CHANGELOG.md
- Commands/Site/UninstallSolution.cs
> Resubmit of PR2529

- CHANGELOG.md
- Commands/ClientSidePages/ConvertToClientSidePage.cs
> Resubmit of PR2539

- CHANGELOG.md
- Commands/Files/GetFile.cs
> Resubmit of PR2550

- CHANGELOG.md
- Commands/Files/GetFolder.cs
- Commands/Files/ResolveFolder.cs
> Resubmit of PR2557 

- CHANGELOG.md
- Commands/Web/SetPropertyBagValue.cs
> Resubmit of PR2544

- Commands/Admin/GetTenantSite.cs
- Commands/Admin/GetWebTemplates.cs
- Commands/Admin/RemoveTenantSite.cs
- Commands/Admin/SetTenantSite.cs
- Commands/Base/PnPAdminCmdlet.cs
> Resubmit of PR2304

- CHANGELOG.md
- Commands/Base/NewAzureCertificate.cs
- Commands/Base/SPOnlineConnectionHelper.cs
- Commands/Branding/AddJavaScriptBlock.cs
- Commands/Branding/AddJavaScriptLink.cs
- Commands/Branding/DisableResponsiveUI.cs
- Commands/Branding/EnableResponsiveUI.cs
- Commands/Branding/RemoveJavaScriptLink.cs
- Commands/Provisioning/Site/NewProvisioningTemplateFromFolder.cs
- Commands/RecordsManagement/SetInPlaceRecordsManagement.cs
- Commands/Site/SetSite.cs
- Commands/Utilities/IsolatedStorage.cs
> Resubmit of PR2577

- CHANGELOG.md
- Commands/Files/AddFile.cs
> Resubmit of PR2478

- CHANGELOG.md
- Samples/Modules.Install/Install-SharePointPnPPowerShellHelperModule.ps1
> Resubmit of PR2614

- CHANGELOG.md
- Commands/Admin/GetTenantSyncClientRestriction.cs
- Commands/Admin/SetTenantSyncClientRestriction.cs
- Commands/Enums/GrooveBlockOption.cs
- Commands/Model/SPOTenantSyncClientRestriction.cs
- Commands/Properties/Resources.Designer.cs
- Commands/Properties/Resources.resx
- Commands/SharePointPnP.PowerShell.Commands.csproj
N/A
* New SPOTenantSyncClientRestriction Model
* New Get-PnPTenantSyncClientRestriction cmdlet
* New Set-PnPTenantSyncClientRestriction cmdlet;
> Added Get/Set-PnPTenantSyncClientRestriction

- CHANGELOG.md
- Commands/Files/AddFile.cs
> Resubmit of PR2619

- Commands/Base/GetAccessToken.cs
N/A
Cleanup of unused usings and fixed up help text
> Cleanup of Get-PnPAccessToken

- CHANGELOG.md
- Commands/Graph/GetAADUser.cs
- Commands/Graph/GetADUser.cs
- Commands/SharePointPnP.PowerShell.Commands.csproj
Depends on https://github.com/pnp/PnP-Sites-Core/pull/2622 to be merged first
Added `Get-PnPAADUser` cmdlet which allows retrieval of users from Azure Active Directory through the Microsoft Graph API
> Added Get-PnPAADUser cmdlet which allows retrieval of users from AAD

- Commands/Principals/GetUser.cs
N/A
Updated MSDN link to docs link, added SupportedPlatform
> Updated documentation on Get-PnPUser

- Commands/UserProfiles/GetUPABulkImportStatus.cs
- Commands/UserProfiles/GetUserProfileProperty.cs
- Commands/UserProfiles/NewUPABulkImportJob.cs
- Commands/UserProfiles/SetUserProfileProperty.cs
N/A
Some minor cleanup to the UserProfile cmdlets
> Some minor cleanup to the UserProfile cmdlets

- CHANGELOG.md
- Commands/Admin/StartSiteRename.cs
- Commands/Base/PipeBinds/WorkflowSubscriptionPipeBind.cs
- Commands/Workflows/GetWorkflowInstances.cs
- Commands/Workflows/RemoveWorkflowSubscription.cs
- Commands/Workflows/StartWorkflowInstance.cs
> Resubmit of PR2169

- Commands/Provisioning/Tenant/ApplyTenantTemplate.cs
The named role is non-existent, and the SharePoint Administrator is not enough to run this successfully.
> Clarification on needed role to run Apply-PnPTenantTemplate

- Commands/Admin/AddOffice365GroupToSite.cs
- Commands/Admin/NewSite.cs
- Commands/Graph/GetDeletedUnifiedGroup.cs
- Commands/Graph/GetUnifiedGroup.cs
- Commands/Graph/GetUnifiedGroupMembers.cs
- Commands/Graph/GetUnifiedGroupOwners.cs
- Commands/Graph/NewUnifiedGroup.cs
- Commands/Graph/RemoveDeletedUnifiedGroup.cs
- Commands/Graph/RemoveUnifiedGroup.cs
- Commands/Graph/RestoreDeletedUnifiedGroup.cs
- Commands/Graph/SetUnifiedGroup.cs
- Commands/Provisioning/Tenant/NewTenantSequenceTeamNoGroupSite.cs
- Commands/Provisioning/Tenant/NewTenantSequenceTeamNoGroupSubSite.cs
- Commands/Site/AddTeamsTeam.cs
N/A
Renamed Office 365 Group to Microsoft 365 Group following the name change applied by Microsoft
> Renamed Office 365 Group to Microsoft 365 Group

- Commands/Base/InitializePowerShellAuthentication.cs
N/A
Added detailed description with link to YouTube recording showing how this cmdlet can be used. Did some minor code cleanup. Made it available online in the SharePointPnPPowerShellOnline module.
> Minor updates to Initialize-PnPPowerShellAuthentication

- Commands/Admin/NewTenantSite.cs
N/A
Documentation URL fixes on New-PnPTenantSite
> Documentation URL fixes on New-PnPTenantSite

- Commands/InformationManagement/ResetLabel.cs
- Commands/InformationManagement/SetLabel.cs
N/A
Clarified that the cmdlet only works for retention labels and not for sensitivity labels. Minor cleanup as well.
> Cleanup of Set-PnPLabel and Reset-PnPLabel

- Commands/Navigation/AddNavigationNode.cs
- Commands/Navigation/GetNavigationNode.cs
- Commands/Navigation/RemoveNavigationNode.cs
N/A
Updated help text on Get-PnPNavigationNode. Remove-PnPNavigationNode and Add-PnPNavigationNode to also mention that it can be used for the footer
> Updated help text on Get-PnPNavigationNode and Add-PnPNavigationNode

- Commands/Admin/SetTenantSite.cs
N/A
Updated help text on Set-PnPTenantSite to include a working reference to an overview with all LCIDs
> Updated help text on Set-PnPTenantSite

- Commands/Graph/AddSiteClassification.cs
- Commands/Graph/DisableSiteClassification.cs
- Commands/Graph/EnableSiteClassification.cs
- Commands/Graph/GetAADUser.cs
- Commands/Graph/GetGraphSubscription.cs
- Commands/Graph/GetSiteClassification.cs
- Commands/Graph/NewGraphSubscription.cs
- Commands/Graph/RemoveGraphSubscription.cs
- Commands/Graph/RemoveSiteClassification.cs
- Commands/Graph/RemoveUnifiedGroup.cs
- Commands/Graph/ResetUnifiedGroupExpiration.cs
- Commands/Graph/RestoreDeletedUnifiedGroup.cs
- Commands/Graph/SetGraphSubscription.cs
- Commands/Graph/SetUnifiedGroup.cs
- Commands/Graph/UpdateSiteClassification.cs
N/A
Cleaning up documentation on Graph Cmdlets due to the new Graph Permission attribute being introduced which automatically generates the documentation regarding the required rights already
> Cleanup of documentation on Graph Cmdlets

- CHANGELOG.md
- Commands/ClientSidePages/RemoveClientSideComponent.cs
Added a second example to Remove-PnPClientSideComponent.
Added a few lines with an example
> Added additional example for Remove-PnPClientSideComponent

- Commands/Lists/RemoveListItem.cs
N/A
Updated help text, added supported platform and replaced literal error message by a reference to the resources
> Updated Remove-PnPListItem

- Commands/WebParts/GetWebPart.cs
I added a 3rd example. I also added the expected output. I'm not sure if that's okay or not. Is there a reference guide for how to format CmdletExample segments? Like how to deal with multiple lines, stuff like that? I couldn't find anything.
> Add GetWebparts.cs example

- Commands/Base/PnPConnectionHelper.cs
Resolves issue https://github.com/pnp/PnP-PowerShell/issues/1724
`Connect-PnPOnline -UseWebLogin` will now specifically log on to /_layouts/15/settings.aspx to ensure faster login performance.
**Depends on PnP Sites Core PR https://github.com/pnp/PnP-Sites-Core/pull/2707 to be merged first**
> Optimizing login speed with Connect-PnPOnline -UseWebLogin

- Commands/Principals/GetUser.cs
Makes getting eg. AadObjectId or UserPrincipalName much easier.
> Get-PnPUser: add Includes parameter

- Commands/Teams/GetTeamsChannelMessage.cs
NA
Add a correct example for the Get-PnPTeamsChannelMessage cmdlet
> Add example getting channel messages

- Commands/Lists/GetListItem.cs
Replaced alias of % with ForEach-Object. That makes it easier for beginners to understand what's going on.
I just replaced a "%" with a "ForEach-Object"
> Update GetListItem.cs examples

- Commands/Base/InitializePowerShellAuthentication.cs
- Commands/Model/AzureApp.cs
> Added permission scope MSGraph.Directory.ReadWrite.All

- README.md
- Typo in Documentation
N/A
Fixes broken url in readme.md
> Quick update to broken Url

- Commands/ClientSidePages/SetClientSidePage.cs
NA
This PR adds support for page header layout type via the `Set-PnPClientSidePage` cmdlet.
> Feature - header layout support in Set-PnPClientSidePage

- Commands/Provisioning/Tenant/ApplyTenantTemplate.cs
Potentially fixes #2861 (as the error message is the same one I originally encountered).
Starting with the 3.24.2008.0 release, the Apply-PnPTenantTemplate cmdlet failed with the error _Your template contains artifacts that require an access token. Please provide consent to the PnP Management Shell application first by executing: Connect-PnPOnline -Graph -LaunchBrowser_ when connected via an AAD App, that has Sites.FullControl.All and TermStore.ReadWrite.All app only permissions.
When stepping through the latest code (both PnP.Core and PnP.PowerShell), and comparing it to the 3.23.2007.1 release code I noticed the GetAccessToken method in Microsoft.SharePoint.Client.Client.ClientContextExtensions had added the following condition
```
if (PnPProvisioningContext.Current != null)
{ …
```
> Fix ApplyTenantTemplate with AAD App

- Commands/Enums/SiteWebTemplate.cs
- [X ] New Feature
https://github.com/pnp/PnP-PowerShell/issues/1838
Added "GrouplessTeamSite = 1" to the SiteWebTemplate enum
> Added GrouplessTeamSite enum to SiteWebTemplates
